NationalSecurityAgency/emissary

src/main/java/emissary/parser/FillingNIOParser.java, src/main/java/emissary/parser/NIOSessionParser.java, src/main/java/emissary/parser/SimpleNioParser.java
- Forces NIOSessionParser subclasses to log using their class name,
to make it clear which class the message originate from.
- make the logger in NIOSessionParser private
- add a logger for FillingNIOParser, SimpleNioParser
- added a debug message to indicate when FillingNIOParser is going into
chunk mode.
=> Closes #10 - Tweak logging in NIOSessionParser + subclasses

src/main/java/emissary/parser/FillingNIOParser.java, src/main/java/emissary/parser/NIOSessionParser.java, src/main/java/emissary/util/WindowedSeekableByteChannel.java
- Eliminated fill path in `loadOrFillNextRegion` when doing `nextChunkOrDie` - going down this path would prevent us from reading sessions larger than the 10k buffer allocated when using this path, and doesn't really eliminate the need for allocating large byte arrays which would cause the OOME in the first place.
- Eliminated the need for channel size checking in `NIOSessionParser` to handle cases where the channel size is unknown or estimated (e.g streaming, `WindowedSeekableByteChannel`) (from @pcgrenier in #9)
- Added significantly more debug logging to `WindowedSeekableByteChannel`
- Can we test this better?
=> Cleanup NIO Reading/Parsing base classes

src/main/java/emissary/test/core/ExtractionTest.java
We need to be able to specify the value of the alternate view. There is an inputAlternateView, but the value is just set to the payload data.
=> updated emissary test setup to add alternate view

src/main/java/emissary/parser/FillingNIOParser.java, src/main/java/emissary/parser/NIOSessionParser.java, src/main/java/emissary/parser/SessionParser.java, src/main/java/emissary/parser/SessionProducer.java, src/main/java/emissary/parser/SimpleNioParser.java
- avoids allocating the entire `maxChunkSize` up-front, allocates `minChunkSize` and then re-allocates as necessary to read an entire session in `NIOSessionParser`
- eliminates some of the confusion around returning null vs. throwing an exception in loadNextRegion in `NIOSessionParser`
- adds documentation to `NIOSessionParser`
- `FillingNIOParser` now properly slides through the chunk, dropping the sessions that are successfully parsed. This should keep the size of the allocated chunkBuffer in `NIOSessionParser` to a minimum.
=> Further nio parser improvements

src/main/java/emissary/parser/FillingNIOParser.java, src/main/java/emissary/parser/NIOSessionParser.java
- When the entire buffer was not consumed but the buffer was
not large enought to contain the entire session, we would reposition
the channel at the beginning of the unread session and re-read
that session into the beginning of the buffer.
Instead of doing that, simply compact the buffer, which has
the effect of moving the data in the buffer to the beginning of the buffer.
Subsequent reads can be made from the current position of the channel.
=> Updates strategy for handling partial session parser reads

src/main/java/emissary/util/io/FileManipulator.java, src/main/java/emissary/util/shell/Executrix.java, src/test/java/emissary/util/shell/ExecutrixTest.java
Replace use of System.currentTimeMillis() with System.nanoTime() to generate part of temporary directory names to avoid name collisions when these are generated by from different threads at about the same time.
=> EM-4461: Fix directory name collisions

src/main/java/emissary/core/MetricsFormatter.java, src/main/java/emissary/core/ResourceWatcher.java, src/test/java/emissary/core/ResourceWatcherTest.java
Currently the reset deletes the namespace and any active timers will not report once they complete. The new system deletes saved values while preserving the namespace.
=> Resource Watcher Fix

src/main/java/emissary/output/DropOffUtil.java
This method is called for each BaseDataObject and String.split() is a very expensive call in terms of objects created. The new code does the same job without creating any objects.
=> Improve performance of emissary.output.DropOffUtil.processMetadata() by eliminating String.split()

src/main/java/emissary/client/EmissaryClient.java
- A server could negotiate with an emissary client to use HTTP basic authentication and thus coax it to send credentials with a reversible encoding. This change updates emissary's client code to use digest authentication exclusively and fail otherwise.
=> Update EmissaryClient to exclusively use HTTP digest authentication

src/main/java/emissary/output/DropOffUtil.java, src/main/java/emissary/server/api/Env.java, src/main/java/emissary/server/api/Pause.java, src/main/java/emissary/server/api/Shutdown.java, src/main/java/emissary/server/mvc/TransferDirectoryAction.java, src/main/java/emissary/server/mvc/internal/RegisterPeerAction.java, src/main/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeAction.java, src/test/java/emissary/pickup/FTestFailedPickupClient.java, src/test/java/emissary/server/mvc/internal/WorkSpaceClientSpaceTakeActionTest.java
Address CodeQL security findings.  (Partially) addresses #171
=> emissary-171: addressed most easily remedied CodeQL security findings

src/main/java/emissary/pool/AgentPool.java, src/test/java/emissary/pool/AgentPoolTest.java
The configurable property can override this.
=> Add max of 50 to computed agents. 

src/main/java/emissary/output/DropOffUtil.java, src/main/java/emissary/output/filter/AbstractFilter.java, src/main/java/emissary/output/filter/DataFilter.java, src/test/java/emissary/output/DropOffUtilTest.java
This method is called for each BaseDataObject and creates a new TreeMap each time along with a bunch of TreeMap$Entry objects. This can be reduced to reusing a single Map object with no Entry objects being created.
=> Improve performance of emissary.output.DropOffUtil.processMetadata() by improving getCookedParameters.

src/main/java/emissary/output/DropOffUtil.java, src/test/java/emissary/output/DropOffUtilTest.java
Corrects minor regression in PR #160
=> extractFileExtensions should only extract extensions after a '.'

src/main/java/emissary/util/magic/MagicNumber.java
This debug statement is not parameterized and ends up being rather expensive when done many many times. I opted to just remove it in this pr for simplicity.
=> Remove expensive debug print from MagicNumber

pom.xml
Note: you must be compile with JDK8 or the plugin will fail.
=> Updated Google error-prone plugin to 2.10.0

src/main/java/emissary/config/ConfigUtil.java, src/main/java/emissary/config/ServiceConfigGuide.java, src/test/java/emissary/config/ConfigUtilTest.java, src/test/java/emissary/config/ServiceConfigGuideTest.java
This is in reference to NationalSecurityAgency/burrito-grande#803.
Updated the error message that is output when an IMPORT_FILE within a config file cannot be found or DNE to make it more clear to Devs what is wrong.
=> Improved error message on config IMPORT_FILE fail

src/main/java/emissary/util/shell/Executrix.java
While going through the "execute" methods within the Executrix, I found a mistake.
https://github.com/NationalSecurityAgency/emissary/blob/0326a8c391a00371709f2d21f29d537e9dabf098/src/main/java/emissary/util/shell/Executrix.java#L652
The above line should be formatted like:
https://github.com/NationalSecurityAgency/emissary/blob/0326a8c391a00371709f2d21f29d537e9dabf098/src/main/java/emissary/util/shell/Executrix.java#L649
This updates the line to err.append(berr.toString()); rather than appending the err.toString().
=> Fixing a single line mistake within Executrix.java

pom.xml
Covers dependabot alert attempted to be handled in https://github.com/NationalSecurityAgency/emissary/pull/217 
https://github.com/NationalSecurityAgency/emissary/security/dependabot/5
=> dependabot: update jackson to 2.12.6 and jackson-databind to 2.12.6.1

src/main/java/emissary/util/LineTokenizer.java, src/test/java/emissary/util/LineTokenizerTest.java
Fixing LineTokenizer.nextTokenBytes to move the index to the end once we have reached the end of the string. Updated unit tests.
=> Fixing LineTokenizer.nextTokenBytes to move the index to the end

pom.xml
Update some of the dependencies covered in https://github.com/NationalSecurityAgency/emissary/pull/201 while avoiding some of the api breaking or gnarly ones.
- rhino usage was removed in https://github.com/NationalSecurityAgency/emissary/pull/177
=> multiple dependency updates, remove rhino

src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java
The need for these methods was removed in version 4.0.0 when the war was removed from Emissary. Look at commits a7eb3739 -> 2b16145d.
This also addresses a codeql warning in #242
=> remove unused workspace adapter code

pom.xml
Updated from 0.8.4 to 0.8.8 - changelog available at: https://www.jacoco.org/jacoco/trunk/doc/changes.html
=> (Minor) Update Jacoco to latest version

pom.xml
Since JGit doesn't support git worktrees, the commit-id plugin for Maven also doesn't support them. This is a small tweak to tell it to use native git instead. There wasn't any significant performance degradation from what I saw locally.
See issue 215 on that plugin's GH repo for more details.
=> (Minor) Use native git with commit-id plugin

src/test/java/emissary/config/ConfigUtilTest.java, src/test/java/emissary/config/ServiceConfigGuideTest.java, src/test/java/emissary/core/BaseDataObjectTest.java, src/test/java/emissary/core/FTestMovingAgent.java, src/test/java/emissary/core/MetadataDictionaryTest.java, src/test/java/emissary/core/NamespaceTest.java, src/test/java/emissary/kff/ChecksumCalculatorTest.java, src/test/java/emissary/kff/ChecksumResultsTest.java, src/test/java/emissary/kff/KffChainTest.java, src/test/java/emissary/kff/KffDataObjectHandlerTest.java, src/test/java/emissary/kff/KffFileTest.java, src/test/java/emissary/kff/SsdeepTest.java, src/test/java/emissary/parser/SimpleNioParserTest.java, src/test/java/emissary/pickup/WorkBundleTest.java, src/test/java/emissary/pickup/WorkSpaceTest.java, src/test/java/emissary/pickup/file/FTestSpacePlaceInteraction.java, src/test/java/emissary/place/MainTest.java, src/test/java/emissary/place/ServiceProviderPlaceTest.java, src/test/java/emissary/util/ClassLookupCacheTest.java, src/test/java/emissary/util/MetadataDictionaryUtilTest.java, src/test/java/emissary/util/ShortNameComparatorTest.java, src/test/java/emissary/util/search/FastBoyerMooreTest.java
In junit 4, we needed to move fail calls to throw AssertionError because the stacktrace was not printed. As we've updated to junit 5, we can change the methods back to fail because there is an overloaded method to accept the throwable.
=> tests :: updated fail method calls

pom.xml
follow up to #298 -- use local settings.xml to control the git config. Add to local ~/.m2/settings.xml for testing:
```
<profiles>
<profile>
<id>git-sample-profile</id>
<properties>
<git.useNative>true</git.useNative>
</properties>
</profile>
</profiles>
<activeProfiles>
<activeProfile>git-sample-profile</activeProfile>
</activeProfiles>
```
=> pom :: allow for native git for git commit id plugin

pom.xml, src/main/java/emissary/Emissary.java, src/main/java/emissary/command/ServerCommand.java, src/main/java/emissary/util/GitRepositoryState.java
Knowing what version of emissary was actually deployed and running would have been helpful in troubleshooting an issue today.
The goal of this PR was to use the git.properties file that is created by the git-commit-id plugin and store the values in a way that is accessible by the running application. 
I did not create tests yet for GitRepositoryState() If that is something that is deemed necessary then I will do that. 
Sample log message:
```
2022-09-07 23:10:28,537 localhost-8001  INFO emissary.command.ServerCommand -   - Starting Emissary Server - version: 7.9.0-SNAPSHOT - built on 2022-09-07T23:08:38+0000 - git hash: 68d40dc
```
=> Created GitRepositoryState struct for storing git properties and log Git version during server startup

src/main/java/emissary/Emissary.java, src/main/java/emissary/util/GitRepositoryState.java
When integrating the new version log output I found it to be confusing to not have the application in the message. Especially if the banner above is for a different down stream component.
Sample message:
```
Emissary Version: 7.9.0-SNAPSHOT - built on 2022-09-16T18:59:59+0000 - git hash: 4781a14
```
=> Add application name to git version log output and remove build username

.github/workflows/maven.yml
This will make the check's fail if a file changes during a build. This is primarily caused by the auto format and changes from it not being committed.
To view an example of the check failing: https://github.com/NationalSecurityAgency/emissary/actions/runs/3260922729/jobs/5354949963
=> Add file change verify to maven builds

pom.xml, src/main/config/emissary.output.DropOffPlace.cfg, src/main/config/logback.xml, src/main/resources/emissary/output/DropOffPlace.cfg
We need a way to control what logback appenders are enabled based on the environment that they are running in.
This will enable/disable the object metrics appender based on an environment variable.
I still need to test this more to see if this will work.
=> Add environment check to enable object metrics appender

src/main/java/emissary/core/MobileAgent.java
In order to show this, I had to re-work the place configs to force a collision where both DevNullPlace and CachePlace had the same SERVICE_NAME to show the error message and the behavior where we visited CachePlace first, tried to go to DevNullPlace but realized there was a parallel entry, rejected it and moved on ultimately to the next phase.
```
2022-11-18 20:43:13,801 localhost-8001 DEBUG emissary.core.MobileAgent - sample.dat - nextKeyFromDirectory found CASE.CACHE.ANALYZE.http://localhost:8001/DevNullPlace$5050
2022-11-18 20:43:13,801 localhost-8001 ERROR emissary.core.MobileAgent - sample.dat - Rejecting parallel entry found for CASE.CACHE.ANALYZE.http://localhost:8001/DevNullPlace$5050: visitedPlaces=[CACHE]
2022-11-18 20:43:13,801 localhost-8001 DEBUG emissary.core.MobileAgent - …
```
=> change rejected parallel entry message from debug to error

src/main/java/emissary/core/TransformHistory.java
Kryo deserialization requires a default constructor, but it's fine if it's visibility is `private`
=> Added default CTOR to support Kryo deserialization

src/main/java/emissary/command/WhatCommand.java, src/main/java/emissary/core/Form.java, src/main/java/emissary/core/constants/Configurations.java, src/main/java/emissary/core/constants/Parameters.java, src/main/java/emissary/output/DropOffUtil.java, src/main/java/emissary/output/filter/DataFilter.java, src/main/java/emissary/pickup/PickUpPlace.java, src/main/java/emissary/pickup/file/FilePickUpClient.java, src/main/java/emissary/place/CoordinationPlace.java, src/main/java/emissary/place/MultiFileUnixCommandPlace.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/main/java/emissary/place/UnixCommandPlace.java, src/main/java/emissary/place/sample/ToLowerPlace.java, src/main/java/emissary/place/sample/ToUpperPlace.java, src/main/java/emissary/transform/HtmlEscapePlace.java, src/main/java/emissary/transform/JavascriptEscapePlace.java, src/main/java/emissary/transform/JsonEscapePlace.java, src/main/java/emissary/util/CharsetUtil.java, src/main/java/emissary/util/DataUtil.java, src/main/java/emissary/util/MetadataDictionaryUtil.java, src/main/java/emissary/util/shell/Executrix.java, src/main/java/emissary/util/web/HttpPostParameters.java, src/test/java/emissary/core/FTestMovingAgent.java, src/test/java/emissary/output/DropOffUtilTest.java, src/test/java/emissary/pickup/file/FilePickUpClientTest.java, src/test/java/emissary/place/FTestCoordinatePlace.java, src/test/java/emissary/place/FTestSkippingCoordinationPlace.java, src/test/java/emissary/transform/HtmlEscapePlaceTest.java, src/test/java/emissary/util/DataUtilTest.java, src/test/java/emissary/util/LineTokenizerTest.java
We have classes for Form (form and filetype) and Family that contain constants that are reusable. There are a bunch of string literals and constants that are riddled throughout the code base that seem like it would be helpful to consolidate into one location, e.g. event-date, original-filename, document-title. This is an initial attempt at moving some of the duplicated string literals -- marking this as discussion to hear any thoughts.
=> attempting to consolidate constants into classes

src/main/java/emissary/Emissary.java, src/main/java/emissary/command/EnvCommand.java
Env output command:
```
./emissary env
________  ________ _____ _____  ___  ________   __
|  ___|  \/  |_   _/  ___/  ___|/ _ \ | ___ \ \ / /
| |__ | .  . | | | \ `--.\ `--./ /_\ \| |_/ /\ V /
|  __|| |\/| | | |  `--. \`--. \  _  ||    /  \ /
| |___| |  | |_| |_/\__/ /\__/ / | | || |\ \  | |
\____/\_|  |_/\___/\____/\____/\_| |_/\_| \_| \_/
Emissary Version: 7.12.0-SNAPSHOT - built on 2022-12-15T14:01:09-0500 - git hash: 43f0365
PROJECT_BASE is set to /Users/connor/Projects/work/emissary/target
Setting emissary.config.dir to /Users/connor/Projects/work/emissary/target/config
Setting emissary.bin.dir to /Users/connor/Projects/work/emissary/target/bin
Setting emissary.output.root to /Users/connor/Projects/work/emissary/target/localoutput
Emissary error dir set to …
```
=> sonarlint :: Remove duplicate log configuration code from EnvCommand

pom.xml
Just removes a property that is no longer supported by the plugin.  It causes IntelliJ to mark the pom with errors.
Its presence doesn't do anything - I verified the site builds the same with or without it.  Removing it just removes errors that we need to ignore from the IDE.
=> Remove deprecated configuration property dependencyLocationsEnabled

src/main/java/emissary/config/ConfigUtil.java, src/test/java/emissary/config/ConfigUtilTest.java
The method, hasConfigErrors, was needed in Jetty 6 to halt startup when there were config issues. The class that called this method was refactored/removed, so it appears that this is no longer needed.
=> Remove hasConfigErrors from ConfigUtil

src/main/java/emissary/kff/KffFile.java, src/main/java/emissary/output/DropOffUtil.java, src/main/java/emissary/parser/ParserFactory.java, src/main/java/emissary/util/WindowedSeekableByteChannel.java
Attempting to solve sonar bug reports for casting operands before assignment: 
- in-line cast to make as little impact as possible
- promote numeric values
=> sonarlint :: cast long operands before assignment

src/main/java/emissary/core/DiffCheckConfiguration.java, src/main/java/emissary/core/IBaseDataObjectDiffHelper.java, src/main/java/emissary/core/IBaseDataObjectHelper.java, src/main/java/emissary/util/PlaceComparisonHelper.java, src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java, src/test/java/emissary/util/PlaceComparisonHelperTest.java
Fundamentally this PR can be considered as two parts:
- refactor `IBaseDataObjectHelper` to move all the diff-related methods to a separate, new class called `IBaseDataObjectDiffHelper`
- introduce a `DiffCheckConfiguration` class to help tidy up the various places where options can be passed in to customise diff behaviour.
=> Refactor diff methods into a more cohesive structure

.github/workflows/codeql-analysis.yml, .github/workflows/maven.yml
This updates the maven and codeql action to the latest checkout version.
Previous version gives a warning due to node.js actions being deprecated
=> update actions checkout to 3.3.0

src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java, src/main/java/emissary/core/channels/FileChannelFactory.java, src/main/java/emissary/core/channels/FillChannelFactory.java, src/main/java/emissary/core/channels/InputStreamChannelFactory.java, src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java, src/test/java/emissary/core/channels/FileChannelFactoryTest.java
We spotted this earlier as a potential source of bugs (indeed, `FileChannelFactory` would likely exhibit this behaviour), and would like to resolve it sooner rather than later before more implementations get created downstream (we're not aware of any that would result in having to co-ordinate this release with integration work though).
The old behaviour relied on a child class of `AbstractSeekableByteChannel` to update the position of the channel during the read, but this could easily be forgotten. This change moves this into Abstract to avoid the implementer having to do this in every `readImpl` override.
=> Move position update during read up to AbstractSeekableByteChannel

src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java, src/main/java/emissary/core/channels/FileChannelFactory.java, src/main/java/emissary/core/channels/FillChannelFactory.java, src/main/java/emissary/core/channels/InputStreamChannelFactory.java, src/main/java/emissary/core/channels/SeekableByteChannelHelper.java, src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java, src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java, src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
This builds on #393 by also right-sizing the provided byteBuffer to avoid reading more than we should, and abstracting this away from implementations. Now, the provided byteBuffer to implement against will have the right amount of remaining bytes to read into based on its position and capacity.
This PR is blocked until #393 is merged.
=> Simplify AbstractSeekableByteChannel by right-sizing the provided byteBuffer

pom.xml
Fixes - 'com.google.common.net.HostAndPort' is marked unstable with @Beta
=> bump guava to 31.1

pom.xml
This change addresses the build warning:
```
[WARNING] Javadoc Warnings
[WARNING] warning: The -footer option is no longer supported and will be ignored.
[WARNING] It may be removed in a future release.
[WARNING] 1 warning
```
=> Remove javadoc footer option to address build warnings

src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java
This PR improves the test coverage to 100%.
This was verified using "mvn clean verify -Dcode-quality".
=> Improve test coverage for SeekableByteChannelHelper.

DEVELOPING.md, pom.xml
Not sure if this is something we want but thought it was helpful when looking at what dependency could be updated.
By running `mvn site` the reports are generated. The reports can also be generated by using the mvn versions target `mvn versions:display-dependency-updates`
The output with site adds the reports and looks like this:
=> Add maven dependency version reports

pom.xml
I noticed GitHub actions were failing even on Java 8 builds with impsort related errors, looks like it's using a more recent version of Maven (3.9.0 I believe is where they remove the transparent dependency on plexus-utils).
[impsort 1.8.0](https://github.com/revelc/impsort-maven-plugin/pull/65) fixes the issue but requires JDK 11 which we're not ready to go to yet. This PR fixes the issue by explicitly requiring plexus-utils just for this plugin.
I've verified this locally with a Maven 4 alpha and JDK8, and the automatic build should verify this too.
=> Fix builds with more recent versions of Maven, incl GitHub actions

src/main/java/emissary/util/DateTimeFormatParser.java
```
[WARNING] emissary/src/main/java/emissary/util/DateTimeFormatParser.java:[125,64] unchecked conversion
required: java.util.List<java.util.function.Function<java.lang.String,java.time.LocalDateTime>>
found:    java.util.ArrayList
```
=> fix DateTimeFormatParser unchecked conversion build warning

pom.xml
manifested in the build as:
```
[WARNING] Javadoc Warnings
[WARNING] javadoc: warning - Multiple sources of package comments found for package "javax.servlet"
[WARNING] javadoc: warning - Multiple sources of package comments found for package "javax.servlet.http"
```
and using the new feature for  `mvn duplicate-finder:check` these packages conflicted in their resources between javax and jakarta.
The only conflict left is the RollManager.cfg
=> exclude javax.servlet-api and rely on jakarta.servlet-api

src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
```
[WARNING] emissary/src/test/java/emissary/test/core/junit5/RegressionTestUtil.java:168: warning: no description for @param
[WARNING] * @param payload
[WARNING] ^
[WARNING] emissary/src/test/java/emissary/test/core/junit5/RegressionTestUtil.java:169: warning: no description for @param
[WARNING] * @param answers
[WARNING] ^
```
=> address RegressionTestUtil javadoc warnings

pom.xml
Removes the following warnings from the build:
```
[WARNING] Parameter 'overrideConfigCompilerVersion' is unknown for plugin 'formatter-maven-plugin:2.11.0:format (format-java-sources)'
[WARNING] Parameter 'overrideConfigCompilerVersion' is unknown for plugin 'formatter-maven-plugin:2.11.0:format (format-java-test-sources)'
[WARNING] Parameter 'overrideConfigCompilerVersion' is unknown for plugin 'formatter-maven-plugin:2.11.0:format (format-java-sources)'
[WARNING] Parameter 'overrideConfigCompilerVersion' is unknown for plugin 'formatter-maven-plugin:2.11.0:format (format-java-sources)'
```
I went back trying to find what version removed the parameter but can't find it. It was added as a parameter in plugin version 0.1.0: https://github.com/revelc/formatter-maven-plugin/blob/main/CHANGEL …
=> Remove 'overrideConfigCompilerVersion' from formatter configuration

src/main/java/emissary/Emissary.java, src/main/java/emissary/client/response/Directory.java, src/main/java/emissary/client/response/DirectoryList.java, src/main/java/emissary/client/response/DirectoryResponseEntity.java, src/main/java/emissary/command/DirectoryCommand.java, src/main/java/emissary/server/api/Directories.java, src/test/java/emissary/server/api/EmissaryApiTest.java
Built out a command to list all active Emissary directories entryKeys.
Also built out `api/directories`, creating a JSON object of Directory entry information.
Updated EmissaryApiTest for testing of directories api.
=> Built out command to list Emissary Directories

.github/workflows/super-linter.yaml
The helm templates are set up correctly but the super linter action does not view it as valid yaml. So excluding that directory for now. They have an outstanding feature request to add helm linting in a follow on version
=> exclude helm repo from super lint

src/test/java/emissary/spi/ClassLocationVerificationProviderTest.java
When building emissary in a docker container, the classLocPath variable set in ClassLocationVerificationProvider is set as /app/target/classes/ in the ClassLocationVerificationProvider unit tests. This breaks the testVerifyClassInWorkingDirectory unit test, as the unit test is written such that it expects that location path to have "emissary" as a substring. Re-write the tests to make sure that it works in both docker and non-docker builds.
=> 475 updated unit test to not fail in docker

src/main/java/emissary/Emissary.java
After some operational use, there is no need to have the version output at the execution of every command.
This change means the version is only output for the `version` command as one would expect and the `server` command since it has been useful to know what version is starting.
=> Only output version for version command and server startup

README.md, pom.xml
```
mvn versions:display-plugin-updates:
[INFO] The following plugin updates are available:
[INFO]   com.github.ekryd.sortpom:sortpom-maven-plugin ..... 2.15.0 -> 3.2.1
[INFO]   io.github.git-commit-id:git-commit-id-maven-plugin . 4.9.9 -> 5.0.0
[INFO]   maven-assembly-plugin .............................. 3.3.0 -> 3.4.2
[INFO]   maven-checkstyle-plugin ............................ 3.1.1 -> 3.2.1
[INFO]   maven-dependency-plugin ............................ 3.3.0 -> 3.5.0
[INFO]   maven-deploy-plugin ............................. 3.0.0-M1 -> 3.0.0
[INFO]   maven-enforcer-plugin ........................... 3.0.0-M2 -> 3.2.1
[INFO]   maven-failsafe-plugin ........................ 3.0.0-M3 -> 3.0.0-M8
[INFO]   maven-install-plugin ............................ 3.0.0-M1 -> 3.1.0
[INFO] …
```
=> Non impact full Plugin updates

src/main/java/emissary/core/HDMobileAgent.java, src/main/java/emissary/core/MobileAgent.java
This removes the `isInUse` method (which is synchronized) from the `toString` method of HDMobileAgent. They synchronization of this method was resulting in agent statuses containing 'null' as a lastPlaceVisisted value. This was seen after the addition of https://github.com/NationalSecurityAgency/emissary/commit/9cb7a9545ebd596a23f3b3ade5db663e7194f558.
Removing the call of any synchronized methods from `toString()` seems to be the right thing to do but we still need to maintain whether or not the agent is idle. Using an atomic boolean right when we start the `go()` call that persists until we return the agent to the pool should be comprehensive while the agent is "busy". The `isInUse()` check done today checks for empty `payloadList` and a null `arrivalPlace` which get cleared right …
=> remove isInUse check from HDMobileAgent toString()

pom.xml
Fixes the build timestamp in version command:
```
sh emissary version
________  ________ _____ _____  ___  ________   __
|  ___|  \/  |_   _/  ___/  ___|/ _ \ | ___ \ \ / /
| |__ | .  . | | | \ `--.\ `--./ /_\ \| |_/ /\ V / 
|  __|| |\/| | | |  `--. \`--. \  _  ||    /  \ /  
| |___| |  | |_| |_/\__/ /\__/ / | | || |\ \  | |  
\____/\_|  |_/\___/\____/\____/\_| |_/\_| \_| \_/  
Emissary Version: 7.13.0 2023-05-08T23:40:32Z
```
=> Add BUILD_TIMESTAMP property back in pom for version command

src/main/java/emissary/core/Stage.java, src/test/java/emissary/core/MobileAgentTest.java, src/test/java/emissary/core/StageTest.java
Adds a test for the MobileAgent method that interfaces with the Stage class to determine type values. 
During testing it was discovered that providing `Stage.getByName(null)` throws an NPE, so handle that scenario as well.
=> add test for MobileAgent typeLookup and handle null Stage name

pom.xml
This was just released. https://github.com/apache/maven-surefire/releases
Here is the junit diff from the update. This is on par with the M5 updates we've seen where the top level test appears to have "0 tests run" and the nested test counts for all of the annotated test methods (there are 6) as well as the answer file test.
```
< 7, Failures: 0, emissary.transform.HtmlEscapePlaceTest
---
> 0, Failures: 0, emissary.transform.HtmlEscapePlaceTest
> 7, Failures: 0, emissary.transform.HtmlEscapePlaceTest$HtmlEscapePlaceUnitTest
```
=> update to surefire 3.1.0

src/main/java/emissary/core/MetadataDictionary.java, src/main/java/emissary/core/MetricsManager.java, src/main/java/emissary/core/ResourceWatcher.java, src/main/java/emissary/directory/DirectoryPlace.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/main/java/emissary/pool/MobileAgentFactory.java, src/main/java/emissary/server/EmissaryServer.java, src/main/java/emissary/spi/InitializationProvider.java, src/main/java/emissary/spi/MetadataDictionaryInitializationProvider.java, src/main/java/emissary/spi/SPILoader.java
These were other resources not being cleaned up during shutdown. These don't have the negative effects that we were seeing in tests as in #474, but I thought we should attempt to shut them down anyways.
=> shutdown :: additional cleanup

src/main/java/emissary/Emissary.java, src/main/java/emissary/util/io/LoggingPrintStream.java, src/test/java/emissary/util/io/LoggingPrintStreamTest.java
This PR creates a PrintStream with the following goals:
- Be able to use it for StdOut/StdErr.
- Allow only logging by allowing OutputStream to be null.
- Log Throwables as a single log message.
=> Create logging PrintStream for StdOut/StdErr.

src/main/java/emissary/core/MetadataDictionary.java, src/test/java/emissary/core/MetadataDictionaryTest.java, src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/java/emissary/test/core/junit5/TestExtractionTest.java, src/test/resources/emissary/test/core/junit5/MissingTags.xml
Added a null check in MetadataDictionary to prevent future NPE's, and modified the ExtractionTest to consistently fail if we do not create the meta/nometa tags correctly.
=> Consistently fail ExtractionTests if we did not create a meta/nometa tag correctly

pom.xml
This got me yesterday when experimenting with the plugin which led to commits being pushed during the maven build to the master branch.
We don't use the release plugin in our current workflow so disabling the push option should not cause any interruptions. 
I am also of the opinion that in the future if we have a release workflow that the actual git push step should be separate from the maven build
=> Disable push from the maven release plugin

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/util/PayloadUtil.java, src/test/java/emissary/util/PayloadUtilTest.java
Added + to the regex that checks if valid form name and updated unit test. Also updated some comments.
=> 1676 - Allow '+' in IBDO Form name

src/main/java/emissary/util/shell/Executrix.java, src/main/java/emissary/util/shell/ProcessReader.java, src/main/java/emissary/util/shell/ReadOutputBuffer.java, src/main/java/emissary/util/shell/ReadOutputLogger.java, src/test/java/emissary/util/shell/ProcessReaderTest.java
Supports additional context capture in log entries
=> Pass MDC entries down to Executrix child threads 

src/main/java/emissary/util/io/LoggingPrintStream.java
Couldn't think of a good unit test that isn't too clever or too intrusive.  Easiest way to verify the fix is to compare the result of the following steps on this branch vs. target branch:
1, Run `mvn clean package`
2. Run `./emissary agents`
On both branches, the `/.emissary agents` command will spit out the connection refused error message:
```
...
Setting emissary.node.name to localhost 
Setting emissary.node.port to 9001 
Setting emissary.node.scheme to http 
Mon Jul 03 16:04:58 GMT 2023
class org.apache.http.conn.HttpHostConnectException: Connect to localhost:9001 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused (Connection refused)
STDERR : class org.apache.http.conn.HttpHostConnectException: Connect to localhost:9001 [localhost/127.0.0.1, …
```
=> Updated LoggingPrintStream so it won't block application shutdown (targets master)

src/main/java/emissary/output/DropOffPlace.java, src/test/java/emissary/output/DropOffPlaceTest.java
Resolves a potential NullPointerException in `DropOffPlace.agentProcessHeavyDuty`.  (This NPE should never have been possible outside of unit tests anyway.)
=> Added null data check to DropOffPlace completion message setup

src/main/java/emissary/kff/KffDataObjectHandler.java
The 'CHECKSUM_CRC32' parameter key is not removed when calling KffDataObjectHandler.hash(...). This means that if the payload is hashed, then the payload is changed and then the payload is hashed again, there will be two values for the 'CHECKSUM_CRC32' parameter key.
=> Add 'CHECKSUM_CRC32' to the list of removed parameter keys.

src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/main/java/emissary/core/IBaseDataObjectXmlHelper.java, src/main/java/emissary/util/ByteUtil.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java, src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java, src/test/java/emissary/test/core/junit5/RegressionTest.java, src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
This PR accomplishes the following:
- RegressionTest basic behavior changed to sha256 hash IBDO non-printable data instead of base64'ing it.
- Refactor encoders and decoders into their own class so they can be easily changed.
=> RegressionTest updates.

src/main/java/emissary/output/io/DateFilterFilenameGenerator.java, src/test/java/emissary/output/io/DateFilterFilenameGeneratorTest.java
This is similar to https://github.com/NationalSecurityAgency/emissary/blob/master/src/main/java/emissary/output/io/DateStampFilenameGenerator.java
But instead of trying to update that class to what we need figured I would create a new one. I can deprecate the old one if we want. Or just leave it alone
=> Add new Filename Generator with date, node, and filter

src/main/java/emissary/id/UnixFilePlace.java
On another PR that I was checking, saw the UnixFilePlace had a * import.
=> Removing * import from UnixFilePlace

pom.xml, src/main/java/emissary/client/EmissaryClient.java, src/main/java/emissary/client/EmissaryResponse.java, src/main/java/emissary/client/HTTPConnectionFactory.java, src/main/java/emissary/command/AgentsCommand.java, src/main/java/emissary/command/ConfigCommand.java, src/main/java/emissary/command/DirectoryCommand.java, src/main/java/emissary/command/EnvCommand.java, src/main/java/emissary/command/HttpCommand.java, src/main/java/emissary/command/PoolCommand.java, src/main/java/emissary/command/TopologyCommand.java, src/main/java/emissary/directory/HeartbeatManager.java, src/main/java/emissary/pickup/WorkSpace.java, src/main/java/emissary/server/EmissaryServer.java, src/main/java/emissary/server/api/Agents.java, src/main/java/emissary/server/api/Peers.java, src/main/java/emissary/server/api/Places.java, src/main/java/emissary/server/api/Pool.java, src/main/java/emissary/server/api/Version.java, src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java, src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java, src/test/java/emissary/client/EmissaryClientTest.java, src/test/java/emissary/core/FTestMovingAgent.java, src/test/java/emissary/directory/HeartbeatManagerTest.java, src/test/java/emissary/server/EmissaryServerIT.java
`< before change`
`> after change`
```
46,48c46,48
< [INFO] +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
< [INFO] |  +- org.apache.httpcomponents:httpcore:jar:4.4.15:compile
< [INFO] |  \- commons-logging:commons-logging:jar:1.2:compile
---
> [INFO] +- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:compile
> [INFO] |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2.1:compile
> [INFO] |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:compile
```
=> Migrate HttpClient from 4.x to 5.x

.github/workflows/super-linter.yaml
super-linter was migrated from the github namespace, but has not yet received a certified status in the marketplace
=> revert super-linter reference

src/main/config/logback.xml
- resolves issue when `LogObjectMetrics` is not set or null, so the conditional check fails with an error
- removes unknown field for `logLevel` assuming this is the proper list/documentation https://javadoc.io/static/net.logstash.logback/logstash-logback-encoder/4.6/index.html?net/logstash/logback/encoder/LogstashEncoder.html
=> fix object metrics log configuration

src/main/java/emissary/client/response/Directory.java, src/main/java/emissary/directory/DirectoryEntry.java, src/main/java/emissary/directory/DirectoryPlace.java, src/main/java/emissary/server/mvc/DumpDirectoryAction.java, src/main/resources/templates/dump_directory.mustache, src/test/java/emissary/directory/DirectoryEntryTest.java, src/test/java/emissary/server/api/EmissaryApiTest.java
Remove pathWeight instances from code, as well as updating API to no longer show PW in Directories tab.
=> Removing pathWeight from all of Emissary

src/main/java/emissary/config/ServiceConfigGuide.java, src/test/java/emissary/config/ServiceConfigGuideTest.java
ServiceConfigGuide uses java.io.StreamTokenizer to parse the configuration data. StreamTokenizer returns two types of informational tokens, String and Number (i.e. double). ServiceConfigGuide converts Numbers to Strings using Integer.toString(). This limited the range of the number to that of an Integer. A "quick fix" to expand this range is to use Long.toString().
=> Fix ServiceConfigGuide bug.

src/main/java/emissary/core/IBaseDataObjectDiffHelper.java, src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/main/java/emissary/core/constants/IbdoMethodNames.java, src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java
IBaseDataObjectXmlCodec does not currently handle multiple parameter values for a single key correctly when converting XML -> IBDO.
=> Fix IBaseDataObjectXmlCodec bug.

src/test/java/emissary/test/core/junit5/IdentificationTest.java
Extracted the method used to resolve the form from the filename so that method can be overridden in child classes.  Enables decoupling of data file names from the default naming scheme.
=> Allow IdentificationTests to override the strategy used for resolving the expected form

src/main/java/emissary/kff/KffFile.java, src/test/java/emissary/kff/KffFileTest.java
Getting better insight into the cause of any caught `IOException` while searching the KffFile
=> KffFile cleanup

src/main/java/emissary/roll/RollManager.java, src/main/java/emissary/roll/Roller.java, src/test/java/emissary/roll/RollManagerTest.java, src/test/java/emissary/roll/RollableTest.java, src/test/java/emissary/roll/RollerTest.java
Observer/Observable is deprecated as of Java 9, so this updates to use PropertyChangeListener.
=> io :: remove deprecated observer from the roller framework

src/main/config/emissary.core.SafeUsageChecker.cfg, src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java, src/main/java/emissary/core/SafeUsageChecker.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/test/java/emissary/core/BaseDataObjectTest.java, src/test/java/emissary/core/SafeUsageCheckerTest.java, src/test/java/emissary/test/core/junit5/LogbackTester.java
This PR identifies invalid modifications to the IBDO data/array. This pertains only to IBDO data returned as a byte array since data returned as a ChannelFactory is immutable. An invalid modification is when a byte array is returned, the elements are modified and IBDO.setData(...)/IBDO.setChannelFactory(...) is NOT called. The problem occurs when the IBDO data is backed by a channel factory, a byte array is created and returned from the ChannelFactory, the byte array is modified and then the place competes with the byte array being garbage collected without the modifications being given back to the IBDO.
=> Identify invalid IBDO data/array modifications.

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java, src/main/java/emissary/kff/KffDataObjectHandler.java, src/test/java/emissary/kff/KffDataObjectHandlerTest.java
A given object should have only one value for each type of hash we compute.  With this change, the last one computed wins.  Need to make sure that's the behavior we want. 
Honestly, we should _probably_ instead modify the behavior so that the `hash` method hashes a given payload at-most one time (so the computed hashes represent the data in its original form), with any subsequent calls being no-op'ed.
=> Modified KffDataObjectHandler.hash(..) method so it explicitly replaces IBDO params it generates.

src/main/java/emissary/kff/KffFile.java, src/test/java/emissary/kff/KffFileTest.java
Verified that KffFileTest.testConcurrentKffFileCheckCalls() passes with synchronization in place, fails with the synchronization disabled
=> Reverted KffFile back to using RandomAccessFile for file I/O, but now synchronizing access to its use

src/main/java/emissary/util/io/ResourceReader.java, src/test/java/emissary/util/io/ResourceReaderTest.java
I'm not sure of a use case where this would not be the desired behavior? It certainly prevents reasonable resource loading today for any file with an extension.
=> allow "." character in name of ResourceReader resources

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java, src/test/java/emissary/core/BaseDataObjectTest.java
This PR adds a convenience method to the IBaseDataObject to create an InputStream from either the byte[] or SeekableByteChannelFactory that defines the data.
=> Add a newInputStream() to the IBaseDataObject.

src/main/java/emissary/core/DiffCheckConfiguration.java, src/main/java/emissary/core/IBaseDataObjectDiffHelper.java, src/test/java/emissary/core/DiffCheckConfigurationTest.java, src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
Currently, IBaseDataObjectDiffHelper returns all of the parameter keys and values for both IBDO's if there is any difference. This can make finding the actually differences difficult if there are a lot of parameters.
This PR does the following:
1. Add an option to display only the keys that differ for both IBDO's.
2. Add an option to display only the keys and values that differ for both IBDO's.
3. Make No. 1 the default behavior instead of the current behavior.
=> Add additional IBDO parameter diff options.

src/test/java/emissary/util/DisposeHelperTest.java
Fixed an initialization race condition that occurred in DisposeHelperTest class.
=> Fixed Initialization Race Condition in DisposeHelperTest

src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java, src/test/java/emissary/test/core/junit5/RegressionTest.java
This PR updates RegressionTest to sha256 hash non-printable alternate views instead of converting them to printable bytes using base64.
=> Update RegressionTest to hash alternate views instead of base64 converting.

src/test/java/emissary/test/core/junit5/LogbackTester.java, src/test/java/emissary/test/core/junit5/LogbackTesterTest.java
Improved interface of LogBackTester and created test to test LogBackTester.
=> Improve LogBackTester interface

src/test/java/emissary/test/core/junit5/RegressionTest.java
Conditional generation of SHA-256 hash of the view bytes
=> Updated RegressionTest so its handling of alternate views mirrors its handling of primary views

src/main/java/emissary/core/constants/Parameters.java, src/main/java/emissary/output/DropOffUtil.java, src/test/java/emissary/output/DropOffUtilTest.java
Modifying DropOffUtil.extractUniqueFileExtensions() to support full file paths and adding FILE_ABSOLUTEPATH as a field to look in to populate the FILEXT field on the IBDO. The existing behavior only used the Original-Filename field to populate FILEXT. 
As part of this change, I also added a static method DropOffUtil.getBestFilenames() that looks at the IBDO in the FILE_ABSOLUTEPATH and Original-Filename fields and returns all values found in both of those fields.
=> Using FILE_ABSOLUTEPATH and Original-Filename to populate FILEXT

src/main/resources/public/js/emissary.js, src/main/resources/templates/dump_directory.mustache
Built out the code to add a table search in DumpDirectory API to be able to better see active places.
=> Adding search ability in directory action in API

src/main/java/emissary/core/Factory.java
```
[WARNING] /home/runner/work/emissary/emissary/src/main/java/emissary/core/Factory.java:[63,103] found raw type: java.lang.Class
missing type arguments for generic class java.lang.Class<T>
```
=> fix Class raw type warning in Factory.java

src/main/java/emissary/core/HDMobileAgent.java, src/main/java/emissary/core/MobileAgent.java, src/main/java/emissary/place/CoordinationPlace.java
```
[WARNING] /home/runner/work/emissary/emissary/src/main/java/emissary/core/MobileAgent.java:[343,28] auto-closeable resource timer is never referenced in body of corresponding try statement
[WARNING] /home/runner/work/emissary/emissary/src/main/java/emissary/place/CoordinationPlace.java:[201,32] auto-closeable resource tr is never referenced in body of corresponding try statement
[WARNING] /home/runner/work/emissary/emissary/src/main/java/emissary/core/HDMobileAgent.java:[409,28] auto-closeable resource tr is never referenced in body of corresponding try statement
```
The proposed solution is a bit of a step-back since it does not take advantage of the language feature for AutoCloseable resources. This scenario lives in an edge case where the language doesn't expect a usage where the …
=> address warning for unused TimedResource in t-w-r declarations

src/main/java/emissary/command/BaseCommand.java
```
[WARNING] /home/runner/work/emissary/emissary/src/main/java/emissary/command/BaseCommand.java:[214,46] CONFIG_FILE_PROPERTY in ch.qos.logback.classic.util.ContextInitializer has been deprecated
```
=> update deprecated logback CONFIG_FILE_PROPERTY constant

src/main/java/emissary/util/FlexibleDateTimeParser.java, src/main/resources/emissary/util/FlexibleDateTimeParser.cfg, src/test/java/emissary/util/FlexibleDateTimeParserTest.java
There two few issues with date parsing in java 8 that should be resolved in java 11. The point of this ticket is to make sure our date parsing code no longer has issues so we can move over to using the DateTimeFormatter from SimpleDateFormat.
- FlexibleDateTimeParser has a custom workaround of removing offsets from date strings due to an issue with parsing date strings with a time zone and an offset in java 8. The previous behavior would ignore the offset and use the timezone, so we added a custom solution to strip out the three-letter time zone. Now that we are using java11, the modifications are no longer needed so remove this workaround.
- http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8032051. Added a test to make sure our code is successfully able to parse dates that have a …
=> Removing date parsing bug workaround

src/main/java/emissary/place/UnixCommandPlace.java
This update allows a class to extend UnixCommandPlace and override the data-source to process.
=> allow the process data-source to be overridden for UnixCommandPlace

src/main/java/emissary/core/channels/SegmentChannelFactory.java, src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
This PR improved the testing of SegmentChannelFactory primarily by ensuring that closing the channel also closes the underlying SeekableByteChannel.
=> Improve SegmentChannelFactory testing.

src/main/java/emissary/output/DropOffUtil.java, src/main/java/emissary/util/TimeUtil.java, src/test/java/emissary/util/TimeUtilTest.java
=> remove deprecated timeutil methods

pom.xml
this activates when running `mvn clean verify`
=> fail builds when duplicate resources detected

pom.xml
Appears to be a straightforward bump up of the version
Release notes:
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.14
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15
=> Updating jackson dependencies to 2.15.2

pom.xml
Test cases look good.
Release notes:
https://github.com/google/guava/releases
Conflicting reports of availability.
Drafting pending further verification.
=> guava 32.0.0-jre -> 32.1.2-jre

pom.xml
Test cases look good.
Release notes:
https://commons.apache.org/proper/commons-lang/changes-report.html#a3.13.0
Conflicting reports of availability.
Drafting pending further verification.
=> commons-lang 3.12.0 -> 3.13.0

src/main/java/emissary/core/sentinel/Sentinel.java
Super simple fix to replace deprecated defaultString with non-deprecated format and remove maven-compiler warning.
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html
`[defaultString]
Returns either the passed in String, or if the String is null, an empty String ("").`
=> Remove deprecated defaultString()

src/main/java/emissary/core/IBaseDataObjectDiffHelper.java
This PR fixes the below two SONAR warnings for emissary.core.IBaseDataObjectDiffHelper:
- "Define a constant instead of duplicating this literal "parameters" 3 times."
- "Define a constant instead of duplicating this literal "%s%s: %s : %s" 3 times."
=> Fix SONAR warnings for IBaseDataObjectDiffHelper.

src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java, src/test/java/emissary/core/channels/FileChannelFactoryTest.java, src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
Decided to remove the try-with-resources blocks altogether to resolve the build warnings. If needed, I can make them try-finally so that there aren't any "explicit call to close()" warnings.
=> Addressing auto-closeable warnings

pom.xml
Test cases look good.
Release notes:
https://commons.apache.org/proper/commons-compress/changes-report.html#a1.22
https://commons.apache.org/proper/commons-compress/changes-report.html#a1.23.0
https://commons.apache.org/proper/commons-compress/changes-report.html#a1.24.0
Conflicting reports of availability.
Drafting pending further verification.
=> commons-compress 1.21 -> 1.24.0

pom.xml
this came in with https://github.com/NationalSecurityAgency/emissary/commit/ea905bb2a69f8f88d9943ac3b8bf5bbc135b8614 but it may not be needed anymore?
=> remove janino dependency

src/test/java/emissary/test/core/junit5/RegressionTest.java
A small improvement to the usability of the RegressionTest class. I updated the `generateAnswers` method to return true when the system property `generateAnswers=true` or false otherwise. This does not change the default behavior and still allows for the method to be overridden as an option.
However, it allows you to generate/re-generate answers files directly from the command line with maven without having to make temporary code changes in your test classes:
```shell
mvn test -DgenerateAnswers=true
mvn test -Dtest=MyTests* -DgenerateAnswers=true
```
=> Updated RegressionTest to generate answers from command line

src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/main/java/emissary/core/IBaseDataObjectXmlHelper.java, src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
This PR fixes the below SONAR warning in IBaseDataObjectXmlCodecs.
- "Define and throw a dedicated exception instead of using a generic one." (line 138)
=> Fix SONAR warning in IBaseDataObjectXmlCodecs.

src/main/java/emissary/pickup/PickUpPlace.java, src/main/java/emissary/util/ObjectTracing.java
[This change](https://github.com/NationalSecurityAgency/emissary/pull/630/files) accidentally reverted useObjectTraceLogger back to private (probably due to a rebase issue). Changing it back to protected so it can be referenced by child classes. 
Also deprecating the old utils/ObjectTrace class. The class will be removed at a later date.
=> Changing useObjectTraceLogger variable back to protected

src/main/java/emissary/output/filter/JsonOutputFilter.java
On the path to normalize and use a single FilenameGenerator.
First step since no downstream component uses the jsonOutputFilter
=> Set JsonOutputFilter to use DateFilterFilenameGenerator

pom.xml
Reverts NationalSecurityAgency/emissary#691
Needed for ObjectTracing feature.
=> Revert "remove janino dependency"

pom.xml
- swaps configs from `plugins` section to `pluginManagement`
- moves checkstyle to verify phase
- executes formatter related plugins once before compile
- removes noisy `id` tags for executions
=> reorder configs under pluginManagement section of pom

src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
When PlaceComparisonHelper was updated to have different output styles for differing parameters, RegressionTest used the default style, which is to only show differing keys. This PR updates only RegressionTest to use the more informative differing key/values style.
=> Update RegressionTest difference output style.

src/main/java/emissary/core/channels/BufferedChannelFactory.java
This PR changes the bufferSize passed in to be a maxBufferSize so that the internal buffer can be sized according to the equation "bufferSize = Math.min(sbcf.size(), maxBufferSize)).
=> Optimize BufferedChannelFactory's internal buffer size.

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java
Sonar has the below warning for IBaseDataObject.clone() and BaseDataObject.clone(). There is an IBaseDataObjectHelper.clone(...) method that will do both the partial clone that BaseDataObject.clone() does along with a full clone. Therefore, the clone methods on IBaseDataObject and BaseDataObject are not needed. They are being deprecated in this PR and then will be deleted in a future PR.
--
WARNING:
Remove this "clone" implementation; use a copy constructor or copy factory instead.
--
REASON:
Many consider clone and Cloneable broken in Java, largely because the rules for overriding clone are tricky and difficult to get right, according to Joshua Bloch:
Object’s clone method is very tricky. It’s based on field copies, and it’s "extra-linguistic." It creates an object without calling a …
=> Deprecate IBDO.clone()/BDO.clone() in preparation for deletion per Sonar warning

src/main/java/emissary/admin/Startup.java, src/main/java/emissary/server/EmissaryServer.java, src/test/java/emissary/admin/StartupTest.java, src/test/java/emissary/server/EmissaryServerIT.java
If EmissaryServer is started up not in strict-mode, it still will just log unannounced places that are started up.
In strict-mode, the starting of unannounced places will result in EmissaryServer being shutdown.
Added a test to EmissaryServerIT for this, as well as updated StartupTest based on changes made to Startup.
=> EmissaryServer shutdown when unannounced places are started in strict-mode

pom.xml
Parent issue: https://github.com/NationalSecurityAgency/burrito-grande/issues/2600
Excluding `BooleanParameter` error-prone warnings.
BooleanParameter is just adding comments to things like `runTest(800L, 1500L, 200L, 100L, /* simple= */true);` so that you know what the boolean is referencing, but this just makes the code messier, and really is not necessary at all.
=> Excluding BooleanParameter from error-prone warnings

.github/workflows/maven-release.yml, README.md, pom.xml
Builds on top of: https://github.com/NationalSecurityAgency/emissary/pull/701 and will need to be rebased after.
Site gets published to GitHub pages: https://code.nsa.gov/emissary/
=> github-actions :: publish site to github pages in release action 

src/test/java/emissary/test/core/junit5/TestExtractionTest.java
I was playing around with surefire plugin and when I set `<reuseForks>false</reuseForks>`, I got the following error:
```
[INFO] Running emissary.test.core.junit5.TestExtractionTest$WhyDoYouMakeMeDoThis
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.022 s <<< FAILURE! - in emissary.test.core.junit5.TestExtractionTest$WhyDoYouMakeMeDoThis
[ERROR] emissary.test.core.junit5.TestExtractionTest$WhyDoYouMakeMeDoThis.testExtractionPlace(String)  Time elapsed: 0.022 s  <<< ERROR!
org.junit.platform.commons.PreconditionViolationException: Configuration error: You must configure at least one set of arguments for this @ParameterizedTest
at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
at …
```
=> unit-tests :: remove WhyDoYouMakeMeDoThisExtractionTest

.github/workflows/cherrypick.yml, .github/workflows/codeql-analysis.yml, .github/workflows/linter.yaml, .github/workflows/maven-ci.yml, .github/workflows/maven-release.yml, .github/workflows/maven-version.yml, RELEASING.md
This will have to go in tandem with changes in github to use use a new protected branch as well as jenkins jobs internally to understand the new branch name. Any open PRs will need to be re-targeted as well.
=> switch to using main branch in actions

src/main/java/emissary/command/FeedCommand.java, src/main/java/emissary/command/HttpCommand.java, src/main/java/emissary/core/DataObjectFactory.java, src/main/java/emissary/kff/SpamSumSignature.java, src/main/java/emissary/output/DropOffUtil.java, src/main/java/emissary/output/roller/JournaledCoalescer.java, src/main/java/emissary/util/FlexibleDateTimeParser.java, src/test/java/emissary/core/ResourceWatcherTest.java, src/test/java/emissary/core/channels/ChannelTestHelper.java, src/test/java/emissary/output/filter/DataFilterTest.java, src/test/java/emissary/parser/MyDataIdentifierTest.java, src/test/java/emissary/place/CoordinationPlaceTest.java, src/test/java/emissary/util/EmissaryIsolatedClassLoaderExtension.java, src/test/java/emissary/util/PayloadUtilTest.java, src/test/java/emissary/util/io/LoggingPrintStreamTest.java
```
1 [UnsafeReflectiveConstructionCast]
1 [NonOverridingEquals]
1 [NonCanonicalStaticMemberImport]
1 [NonApiType]
1 [RedundantOverride]
1 [MultiVariableDeclaration]
1 [ModifiedButNotUsed]
1 [LoopOverCharArray]
1 [ImmutableEnumChecker]
1 [EqualsIncompatibleType]
1 [ClassNamedLikeTypeParameter]
1 [BadImport]
1 [AlmostJavadoc]
```
=> errorprone :: tackle a handful of single occurrence rules

src/main/java/emissary/place/ComparisonPlace.java
Places automatically connect themselves when they are created. The internal places within ComparisonPlace will get flagged as "starting up without being announced" if they are not disconnected. This PR disconnects the internal places since they will be executed specifically by ComparisonPlace.
=> Disconnect internal places in ComparisonPlace.

src/main/java/emissary/output/roller/JournaledCoalescer.java
A simple attempt to stop this warning eventually without the chance of downstream breakage.
=> sonarlint :: deprecate finalize method in JournaledCoalescer

pom.xml
Resolves **high** vulnerability in amqp-cleint which is transitive to dropwizard metrics. Latest version of dropwizard upgrades to 5.20.0 of amqp-client
https://ossindex.sonatype.org/component/pkg:maven/com.rabbitmq/amqp-client@5.13.1?utm_source=ossindex-client&utm_medium=integration&utm_content=1.7.0
Emissary SBOM report: https://sbom.sonatype.com/report/T1-118f0f57da8c6b3097cc-e3d8ea0398999-1712343746-99037adeebb341d799462d1f507f865c
After:
```
...
[INFO] +- io.dropwizard.metrics:metrics-graphite:jar:4.2.25:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:4.2.25:compile
[INFO] |  \- com.rabbitmq:amqp-client:jar:5.20.0:compile
...
```
=> upgrade dropwizard metrics to 4.2.25

src/test/java/emissary/test/core/junit5/RegressionTest.java
This PR increases RegressionTest's ability to be extended by removing "final" attributes from methods and increasing the scope of methods.
=> Allow RegressionTest to be more extensible.

.github/workflows/maven-ci.yml, .github/workflows/maven-release.yml
Attempt to fix regression introduced in https://github.com/NationalSecurityAgency/emissary/pull/746 where no slack notifications were being triggered.
=> Check repo name for slack notification

src/main/java/emissary/server/EmissaryServer.java
There was an issue with roll actions trying to roll metrics after the ResourceWatcher was stopped. This switch should allow metrics to be output, close all rollers, and then the ResourceWatcher will stop.
=> shutdown RollManager before ResourceWatcher

src/main/java/emissary/util/FlexibleDateTimeParser.java, src/test/java/emissary/util/FlexibleDateTimeParserTest.java
https://rules.sonarsource.com/java/RSPEC-5850/
https://github.com/NationalSecurityAgency/emissary/security/code-scanning/58
=> update trailing character cleanup regex in FlexibleDateTimeParser

src/main/java/emissary/place/sample/DelayPlace.java
Logging when performing a shutdown of the emissary server now:
```
...
2024-05-15 12:37:17,429 localhost-8001  INFO emissary.core.Pausable -   - emissary.pickup.file.FileDataServer currently paused, sleeping for 60000
2024-05-15 12:37:22,473 localhost-8001  WARN emissary.place.sample.DelayPlace - emissary-knight.png *.DELAY.ANALYZE.http://localhost:8001/DelayPlace - Interrupted before delay expired
java.lang.InterruptedException: sleep interrupted
at java.base/java.lang.Thread.sleep(Native Method)
at emissary.place.sample.DelayPlace.process(DelayPlace.java:44)
at emissary.place.ServiceProviderPlace.processHeavyDuty(ServiceProviderPlace.java:642)
at emissary.place.ServiceProviderPlace.agentProcessHeavyDuty(ServiceProviderPlace.java:591)
at …
```
=> sonarlint :: do not ignore InterruptedException in DelayPlace

src/main/java/emissary/output/filter/JsonOutputFilter.java
Addresses https://cloud-ci.sgs.com/sonar/coding_rules?open=java%3AS2066&rule_key=java%3AS2066 for IbdoParameterFilter
From what I can tell, this was initially committed this way and I believe it to be unnecessary. From what I understand about the use of SimpleBeanPropertyFilter, the implementing class does not need to be serializable as a whole and removing that behavior removes the need to classify it as static.
=> sonarlint :: remove Serializable from JsonOutputFilter inner class

src/test/java/emissary/test/core/junit5/TestingResourcesTest.java, src/test/java/emissary/test/core/junit5/UnitTest.java, src/test/resources/emissary/test/core/junit5/TestingResourcesTest/sample.xml
creates getMyTestAnswerFiles, which allows for test answer files from one directory to work with data files from another directory.
=> adding ability to pull from different directories for test data & answer files

src/main/java/emissary/admin/Startup.java, src/main/java/emissary/command/ServerCommand.java, src/main/java/emissary/command/ServiceCommand.java, src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/EmissaryRuntimeException.java, src/main/java/emissary/core/Factory.java, src/main/java/emissary/output/roller/journal/JournaledChannel.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/main/java/emissary/server/EmissaryServer.java, src/main/java/emissary/util/UnixFile.java, src/main/java/emissary/util/magic/MagicNumber.java, src/main/java/emissary/util/magic/MagicNumberFactory.java, src/test/java/emissary/EmissaryTest.java, src/test/java/emissary/config/ConfigUtilTest.java, src/test/java/emissary/core/FactoryTest.java, src/test/java/emissary/roll/RollManagerTest.java, src/test/java/emissary/util/DisposeHelperTest.java
=> errorprone :: ThrowSpecificExceptions

pom.xml
Hobble the module encapsulation issue
```
Exception in thread "main" java.lang.IllegalAccessError: class com.google.errorprone.BaseErrorProneJavaCompiler (in unnamed module @0x6279cee3) cannot access class com.sun.tools.javac.api.BasicJavacTask (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.api to unnamed module @0x6279cee3
at com.google.errorprone.BaseErrorProneJavaCompiler.addTaskListener(BaseErrorProneJavaCompiler.java:92)
at com.google.errorprone.ErrorProneJavacPlugin.init(ErrorProneJavacPlugin.java:34)
at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugin(BasicJavacTask.java:255)
at jdk.compiler/com.sun.tools.javac.api.BasicJavacTask.initPlugins(BasicJavacTask.java:229)
at …
```
=> 2860 Fix errorProne build 

src/test/java/emissary/test/core/junit5/TestingResourcesTest.java, src/test/java/emissary/test/core/junit5/UnitTest.java
May need minor follow-on work to support PR #821 requirements, but this is sufficient to mitigate thread-safety concerns when running unit tests concurrently.
=> Modifying UnitTest so that alternative answer file location usage is thread-safe

src/main/java/emissary/util/ClassLookupCache.java, src/main/java/emissary/util/ConstructorLookupCache.java, src/main/java/emissary/util/io/FileManipulator.java
https://rules.sonarsource.com/java/RSPEC-5164/
Another somewhat silly warning because having a method and calling that method are two different things, but it doesn't hurt to add a method to provide the capability. I just don't know that it's useful (or necessary to call them) with how we are using these objects since they live for the duration of the application.
=> sonarlint :: add unload method to remove ThreadLocal objects

src/main/java/emissary/directory/HeartbeatManager.java
Fixed HeartbeatManager so workers properly poll the feeder for files.  Successfully testing as command line clients and in docker compose.  Worked with @dev-mlb to identify and resolve this issue.
=> HeartbeatManager bug fix

src/test/java/emissary/test/core/junit5/RegressionTest.java, src/test/java/emissary/test/core/junit5/RegressionTestUtil.java, src/test/java/emissary/test/core/junit5/UnitTest.java
This updates `generateAnswers` to be able to generate answer files in the correct location when `getMyTestParameterFiles` is passed two separate classes. This allows files to generate/regenerate in the provided answer class, based on .dat files in the other class directory.
=> updating RegressionTest generateAnswers for when two classes are used for test .dat & answer files

src/test/java/emissary/util/DependencyCheckTest.java
Resolves initialization bug.  Can reproduce on the "main" branch by executing the test individually (command line or IDE), or by testing with the following command:
```
mvn clean test -Dsurefire.runOrder.random.seed=23112416049778
```
=> DependencyCheckTest: corrected static member initialization

src/main/config/logback.xml, src/main/java/emissary/admin/Startup.java
Startup was updated to use sets, so this adds logging to notify the user that a duplicate class was configured. Ideally we test for this and see if it hits in prod and then later we'll add it to strict mode failures. I also removed the logging of the full location of a place during startup and tried to make the output a little more useful by adding status and class name. Lastly, I added color output to logback to make the logs a little easier to read.
=> Update startup logging

src/test/java/emissary/core/channels/LoggingChannelFactoryTest.java, src/test/java/emissary/core/channels/LoggingInputStreamFactoryTest.java, src/test/java/emissary/test/core/junit5/LogbackTesterTest.java, src/test/java/emissary/util/DisposeHelperTest.java
only occurs when testing classes use `import ch.qos.logback.classic.Logger;` against UnitTest's slf4j logger
=> errorprone :: suppress HidingField

src/test/java/emissary/core/SafeUsageCheckerTest.java, src/test/java/emissary/core/TransformHistoryTest.java, src/test/java/emissary/parser/InputSessionTest.java, src/test/java/emissary/pool/AgentPoolTest.java, src/test/java/emissary/test/core/junit5/LogbackTesterTest.java, src/test/java/emissary/transform/JavascriptEscapePlaceTest.java, src/test/java/emissary/transform/JsonEscapePlaceTest.java, src/test/java/emissary/util/DateTimeFormatParserTest.java, src/test/java/emissary/util/PayloadUtilTest.java
to comply with JUnit5 (and subsequently sonar), public modifiers for test declaration are no longer necessary, so to have it consistent across emissary, went through and changed the tests where public is not needed.
=> removing public modifiers from junit5 tests where applicable

src/main/java/emissary/transform/JsonEscapePlace.java, src/main/java/emissary/transform/decode/JsonEscape.java, src/test/java/emissary/transform/JsonEscapePlaceTest.java, src/test/java/emissary/transform/decode/JsonEscapeTest.java
adding `@Deprecated(forRemoval = true)` for JsonEscapePlace and JsonEscape utility.
removing these and the references in `emissary.admin.ClassNameInventory.cfg` & `places.cfg` will happen later.
=> deprecating JsonEscapePlace and JsonEscape utility

src/test/java/emissary/test/core/junit5/RegressionTest.java, src/test/java/emissary/test/core/junit5/RegressionTestUtil.java
This PR adds an error message when RegressionTest is generating answers and differences are detected. This usually indicates that there is non-deterministic state in the IBDO because the place is executed once to generate the answer file and once to check against the answer file. If these two executions produce different results, then this most likely indicates non-deterministic state.
=> Add RegressionTest error message for when possible non-deterministic behavior is detected.

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java
Currently, the byte[] methods are used almost exclusively compared to these methods.  Additionally, the couple of uses of these methods get the array of bytes from the ByteBuffer and don't use the ByteBuffer.
=> Deprecate IBDO/BDO ByteBuffer methods.

src/main/java/emissary/transform/HtmlEscapePlace.java, src/main/java/emissary/transform/decode/HtmlEscape.java, src/test/java/emissary/transform/HtmlEscapePlaceTest.java, src/test/java/emissary/transform/decode/HtmlEscapeTest.java
adding `@Deprecated(forRemoval = true)` for HtmlEscapePlace and HtmlEscape utility.
removing these and the references in emissary.admin.ClassNameInventory.cfg & places.cfg will happen later.
=> deprecating HtmlEscapePlace and HtmlEscape utility

src/main/java/emissary/transform/JavascriptEscapePlace.java, src/main/java/emissary/transform/decode/JavascriptEscape.java, src/test/java/emissary/transform/JavascriptEscapePlaceTest.java
adding `@Deprecated(forRemoval = true)` for JavascriptEscapePlace and JavascriptEscape utility.
removing these and the references in emissary.admin.ClassNameInventory.cfg & places.cfg will happen later.
=> deprecating JavascriptEscapePlace and JavascriptEscape utility

src/test/java/emissary/test/core/junit5/LogbackTester.java
This PR fixes LogbackTester so that it accepts Exceptions in log statements that do not have a message (i.e. the message is 'null').
=> Fix LogbackTester bug which did not allow Exceptions with no (i.e. null) messages.

src/main/java/emissary/admin/Startup.java, src/main/java/emissary/client/EmissaryClient.java, src/main/java/emissary/command/converter/FileExistsConverter.java, src/main/java/emissary/command/converter/PathExistsConverter.java, src/main/java/emissary/core/DiffCheckConfiguration.java, src/main/java/emissary/core/channels/InputStreamChannelFactory.java, src/main/java/emissary/kff/ChecksumCalculator.java, src/main/java/emissary/kff/KffFile.java, src/main/java/emissary/kff/KffMemcached.java, src/main/java/emissary/kff/SpamSumSignature.java, src/main/java/emissary/output/filter/JsonOutputFilter.java, src/main/java/emissary/output/io/SimpleFileNameGenerator.java, src/main/java/emissary/output/roller/JournaledCoalescer.java, src/main/java/emissary/util/CaseInsensitiveMap.java, src/main/java/emissary/util/UnixFile.java, src/main/java/emissary/util/io/FileFind.java, src/main/java/emissary/util/io/ReadOutput.java, src/main/java/emissary/util/roll/RollableFileOutputStream.java, src/main/java/emissary/util/search/ByteTokenizer.java, src/main/java/emissary/util/search/KeywordScanner.java, src/main/java/emissary/util/search/MultiKeywordScanner.java
soft reset and rebase of https://github.com/NationalSecurityAgency/emissary/pull/842
=> errorprone :: FieldCanBeFinal

src/main/java/emissary/pickup/WorkSpace.java
`static variable should not be accessed from an object instance`
cleans up sonar complaining about this as well
=> errorprone: StaticQualifiedUsingExpression

src/main/java/emissary/Emissary.java
This appears to be flagging the EMISSARY_COMMANDS Map which is using an `unmodifiableMap` call, so I believe this to be a false positive. Unfortunately, the suppression needs to go on the encapsulating class but this solution seems better than converting to using the suggested google class for `ImmutableMap`.
=> errorprone: ImmutableMemberCollection - suppressing in Emissary class

src/main/java/emissary/util/web/Url.java, src/main/java/emissary/util/web/UrlData.java, src/test/java/emissary/util/web/UrlDataTest.java
```
[WARNING] /nsa-emissary/src/main/java/emissary/util/web/Url.java:[79,91] [AvoidObjectArrays] Avoid accepting a UrlRequestProperty[]; consider an Iterable<UrlRequestProperty> instead
(see https://errorprone.info/bugpattern/AvoidObjectArrays)
[WARNING] /nsa-emissary/src/main/java/emissary/util/web/Url.java:[118,92] [AvoidObjectArrays] Avoid accepting a UrlRequestProperty[]; consider an Iterable<UrlRequestProperty> instead
(see https://errorprone.info/bugpattern/AvoidObjectArrays)
[WARNING] /nsa-emissary/src/main/java/emissary/util/web/UrlData.java:[30,113] [AvoidObjectArrays] Avoid accepting a UrlRequestProperty[]; consider an Iterable<UrlRequestProperty> instead
(see https://errorprone.info/bugpattern/AvoidObjectArrays)
[WARNING] …
```
=> errorprone :: AvoidObjectArrays in Url and UrlData

src/main/java/emissary/kff/KffDataObjectHandler.java, src/test/java/emissary/kff/KffDataObjectHandlerTest.java
Also added missing test coverage
=> Fixing missed negation in KffDataObjectHandler.previouslyComputedMd5HasChanged

pom.xml
- drop numeric portion in name for deps
- use "plugin." for plugin versions instead of "dep."
- annotate all plugin versions used
- sync jxr plugin on 3.3.0 (it was called out twice with different versions)
If this went too far with annotating all the versions I can scale it back, but having an easy way to find all plugin versions was nice.
=> update 'dep.' names and use 'plugin.' prefix for plugins in pom

src/main/java/emissary/output/filter/AbstractFilter.java, src/test/java/emissary/output/filter/AbstractFilterTest.java
Can now configure the allowed characters in a denylist entry. 
Use Regex format. e.g. `ALLOWED_NAME_CHARS = "a-zA-Z0-9_"`
Allowed characters will get substituted into the patterns for view name formatting and character ordering. These regexes can also be configured differently, either using `%s` to substitute the allowed character string, or manually typing out the allowed chars. e.g.:
`VIEWNAME_FORMAT = "^[%s]+(\\.[%s]+)?\\*?$"`
`VIEWNAME_FORMAT = "^[a-zA-Z0-9_]+(\\.[a-zA-Z0-9_]+)?\\*?$"`
=> Made AbstractFilter Denylist settings configurable

.github/release.yml
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
=> exclude github-actions[bot] changes from release notes

src/main/java/emissary/util/FlexibleDateTimeParser.java, src/test/java/emissary/util/FlexibleDateTimeParserTest.java
```
[WARNING] /nsa-emissary/src/main/java/emissary/util/FlexibleDateTimeParser.java:[142,8] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
(see https://errorprone.info/bugpattern/ReturnMissingNullable)
Did you mean '@Nullable static ZonedDateTime lastDitchParsingEffort(final String date) {'?
[WARNING] /nsa-emissary/src/main/java/emissary/util/FlexibleDateTimeParser.java:[99,32] [UngroupedOverloads] Overloads should be grouped together, even when modifiers such as static or private differ between the methods; found ungrouped overloads of 'parse' on line(s): 171, 182
(see https://errorprone.info/bugpattern/UngroupedOverloads)
Did you mean to remove this line?
[WARNING] /nsa-emissary/src/main/java/emissary/util/FlexibleDateTimeParser.java:[111,32 …
```
=> errorprone :: FlexibleDateTimeParser

pom.xml
Upgrading janino to mitigate  CVE: https://nvd.nist.gov/vuln/detail/CVE-2023-33546 to 3.1.12 
More details from[SBOM](https://sbom.sonatype.com/report/T1-a4e79c5353879ed9b588-e3d8ea0398999-1725999270-b61bf2b10f344f5da5d7b440a33e27c1)
Noticed that in the past we tried to remove it but had to revert that change here: https://github.com/NationalSecurityAgency/emissary/commit/9f789d54128bacd42cf4498e9a0e8930b9df8fcb
=> dependencies: upgrade janino dependency to 3.1.12

src/main/java/emissary/core/IBaseDataObjectHelper.java, src/main/java/emissary/core/channels/SeekableByteChannelHelper.java, src/main/java/emissary/kff/KffChain.java, src/main/java/emissary/kff/KffDataObjectHandler.java, src/main/java/emissary/place/KffHashPlace.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java, src/test/java/emissary/kff/KffDataObjectHandlerTest.java
born from https://github.com/NationalSecurityAgency/emissary/pull/368 but without the mandate to use `SeekableByteChannel` for hashing in all cases.
Capture the enhanced testing and exception handling updates for both types of hashing.
=> update kff hash exception handling and SeekableByteChannel interactions

pom.xml
mistake during: https://github.com/NationalSecurityAgency/emissary/commit/4d84b8de0e125961ebebbb99edbaa9df2d613e97
needed so the plugin in line 1422 works:
```
<plugin>
<groupId>org.sonatype.plugins</groupId>
<artifactId>nexus-staging-maven-plugin</artifactId>
<version>${plugin.nexus-staging-maven.version}</version>
<extensions>true</extensions>
<configuration>
<serverId>ossrh</serverId>
<nexusUrl>https://oss.sonatype.org/</nexusUrl>
<autoReleaseAfterClose>true</autoReleaseAfterClose>
</configuration>
</plugin>
```
=> correct param for plugin.nexus-staging-maven.version

src/main/java/emissary/directory/DirectoryObserverManager.java
Silence the warning, but this probably needs a bigger effort to remove this from the ordinal list if we don't want it anymore.
=> errorprone: MissingCasesInEnumSwitch

src/main/java/emissary/place/VersionPlace.java, src/test/java/emissary/place/VersionPlaceTest.java
Basically gets rid of the use of `emissary.util.Version`, and relies on `GitRepositoryState` to get the version and hash. This allows for a lot less code-reusage for classes downstream that extend this.
Created setters for the booleans so they can be set downstream.
One thing to keep in mind for this is the BuildTime is only reset in the `emissary.git.properties` file when "mvn clean" is run
=> updates to VersionPlace for less code-reusage downstream

src/main/java/emissary/util/search/KeywordScanner.java, src/test/java/emissary/util/search/ByteMatcherTest.java, src/test/java/emissary/util/search/KeywordScannerTest.java
Forgot to assign the starting offset to the newStart variable in KeywordScanner. Fixed that and added test.
=> Fixing starting offset of listIndexOf method in KeywordScanner

src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java, src/test/java/emissary/test/core/junit5/RegressionTest.java
This PR updates RegressionTest to assume all byte arrays are UTF-8 and not process them as ASCII (i.e. ISO_8859_1). The main benefit of this is that valid UTF-8 is output in the XML directly instead of being hashed or BASE64'd.
NOTE: This is a potentially "breaking" change that might require XML files to be regenerated.
=> Update RegressionTest to assume UTF-8.

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/test/java/emissary/core/BaseDataObjectTest.java
Not currently needed, and we have git history available if we need to reinstitute it.
=> Removed SafeUsageChecker from BaseDataObject, deprecated IBDO.checkForUnsafeDataChanges

src/main/java/emissary/core/IBaseDataObjectHelper.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java
This PR deprecates the IBaseDataObjectHelper.clone() method that allows for partial clones. Partial clones were implemented to allow cloning that matched the now deprecated BaseDataObject.clone() method. A search of the code bases did not show any instance where IBaseDataObjectHelper.clone() was called for a partial clone except for in the IBaseDataObjectHelperTest class. Therefore, only full clones seem to be needed and partial clones should be removed.
=> Deprecate IBaseDataObjectHelper.clone() that allows partial clones.

pom.xml
```
[WARNING] Parameter 'sourceEncoding' is unknown for plugin 'maven-pmd-plugin:3.20.0:check (default)'
[WARNING] Parameter 'sourceEncoding' is unknown for plugin 'maven-pmd-plugin:3.20.0:pmd (pmd)'
```
=> fix pmd sourceEncoding parameter warning

src/main/java/emissary/util/ShortNameComparator.java, src/test/java/emissary/util/ShortNameComparatorTest.java
This is an updated version of #135 .
=> Improve performance of ShortNameComparator.

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java, src/test/java/emissary/core/BaseDataObjectTest.java
Starting this old thread again
=>  ibdo :: get parameter as string

src/test/java/emissary/core/BaseDataObjectTest.java
addresses build failures from integrating https://github.com/NationalSecurityAgency/emissary/commit/2e798ab650acb3de92981925034bdf6c7fb2c5c1 after https://github.com/NationalSecurityAgency/emissary/commit/504c4921d38e10501d64a1650a4ecd23cb090f41
=> fix BaseDataObjectTest logback imports

src/main/java/emissary/admin/Startup.java, src/main/java/emissary/command/ServerCommand.java, src/main/java/emissary/directory/EmissaryNode.java, src/main/java/emissary/pickup/WorkSpace.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/main/java/emissary/server/EmissaryServer.java, src/test/java/emissary/server/EmissaryServerIT.java, src/test/java/emissary/server/api/PeersIT.java, src/test/java/emissary/test/core/junit5/FunctionalTest.java, src/test/java/emissary/test/core/junit5/UnitTest.java
- removes the need for node.mode system property (get from command or default value)
- no longer need to check namespace binding to determine state
- deprecate stop/status methods for future cleanup
Pulled out of https://github.com/NationalSecurityAgency/emissary/pull/900 but stops short of changing mode to enum and changing command validator.
=> initialize static instance of EmissaryServer

src/main/java/emissary/core/IBaseDataObject.java
Update `getStringParameter` Javadoc to suggest `getParameterAsString` when a single value is expected, as this is the most common situation and will log a warning is the expectation is violated
=> getStringParameter deprecation should suggest getParameterAsString

pom.xml, src/test/java/emissary/test/util/ComplexUnicodeSamples.java, src/test/java/emissary/test/util/ComplexUnicodeSamplesTest.java
There are a few places where we need more robust testing that we aren't making false assumptions about what the byte array contains and how (we attempt) to do clever things with it.  When our code or the 3rd party libraries we use are defaulting to baseless assumptions about how we can  move around in the bytes, we end up mangling the data in ways that isn't always obvious.  This helper class and the explaining test should allow us to test more edge cases, and avoid using dependencies that don't handle Unicode well.   I envision adding more samples as we come across more cases that keep tripping us up, but for now I need the XML map for one of my tickets, and I have plans for the emoji string for a couple of other tests. 
The entirety of this change should be test only, used from the …
=> Adding a utility to provide test data for specific unicode handling issues.

src/main/java/emissary/core/constants/Parameters.java
due to HtmlEscapePlace being deprecated, deprecate this constant as well
=> deprecate SUFFIXES_HTML_ESCAPE constant parameter

src/main/java/emissary/util/shell/TempFileNames.java
Unintentional oversight when it was first added.  No need for it to be package-private, and this change makes it more approachable when mocking Executrix interactions.
=> TempFileNames constructor is now public, not package-private

src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
This PR updates the test code to include checks for the difference messages. This is a precursor to improving the difference messages.
=> Specify difference messages in test code for IBaseDataObjectDiffHelper.

src/main/java/emissary/config/Configurator.java, src/main/java/emissary/config/ServiceConfigGuide.java, src/test/java/emissary/config/ServiceConfigGuideTest.java
Useful for ensuring deterministic order of configured multi-map entries
=> Added Configurator findStringMatchMultiMap overload that takes a preserveOrder flag

src/main/java/emissary/core/channels/InputStreamChannelFactory.java, src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
This PR improves the performance of InputStreamChannelFactory by calculating the size of the InputStream once within the factory instead each time a SeekableByteChannel is created. Additionally, the deprecated CountingInputStream was replaced with BoundedInputStream.
=> Performance improvement for InputStreamChannelFactory.

src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/java/emissary/test/core/junit5/TestExtractionTest.java, src/test/resources/emissary/test/core/junit5/ProcessingErrorTest.xml
Create a way to verify/assert that ProcessingErrors added to the BDO are correct in the testing interface.
=> adding verification for ProcessingErrors in testing answer files

src/main/java/emissary/util/os/OSReleaseUtil.java, src/test/java/emissary/util/os/OSReleaseUtilTest.java, src/test/resources/emissary/util/os/pop22
done for the scenario where ubuntu is not the ID of the OS, but the `ID_LIKE=ubuntu` (see src/test/resources/emissary/util/os/pop22 for example)
=> add ability to check ID_LIKE for ubuntu in OSReleaseUtil

pom.xml
This analyzes the project to find dependencies that are: used and declared; used and undeclared; unused and declared. This check occurs during the `verify` lifecycle phase for maven.
I have it set to currently **NOT** fail on warnings (and this obviously can be changed).
Can also be made to ignore certain groups of warnings (for example, https://maven.apache.org/plugins/maven-dependency-plugin/analyze-only-mojo.html#ignoredusedundeclareddependencies) or individual warnings for dependencies.
=> adding analyze goal to maven-dependency-plugin

src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/test/java/emissary/core/IBaseDataObjectXmlHelperTest.java, src/test/java/emissary/test/core/junit5/RegressionTest.java
This PR adds an optional encoder set that will always hash SeekableByteChannels and alternate view byte arrays without regard to whether the data is "printable". They can be used by any class that extends RegressionTest by overriding the getEncoders() method and returning IBaseDataObjectXmlCodecs.ALWAYS_SHA256_ELEMENT_ENCODERS.
=> Add optional RegressionTest encoders that always hash.

pom.xml
```
[INFO] --- maven-dependency-plugin:3.8.1:analyze-only (analyze) @ emissary ---
[WARNING] Used undeclared dependencies found:
[WARNING]    com.google.code.findbugs:jsr305:jar:3.0.2:compile
[WARNING]    org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:3.1.3:test
[WARNING]    org.junit.jupiter:junit-jupiter-api:jar:5.11.4:test
[WARNING]    org.junit.platform:junit-platform-commons:jar:1.11.4:test
[WARNING]    ch.qos.logback:logback-core:jar:1.5.13:compile
[WARNING]    jakarta.ws.rs:jakarta.ws.rs-api:jar:3.1.0:compile
[WARNING]    org.apache.httpcomponents.core5:httpcore5:jar:5.2.1:compile
[WARNING]    org.eclipse.jetty:jetty-servlet:jar:11.0.24:compile
[WARNING]    org.opentest4j:opentest4j:jar:1.3.0:test
[WARNING] …
```
=> add undeclared deps, remove unused deps, tidy up management

src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/java/emissary/test/core/junit5/TestExtractionTest.java, src/test/resources/emissary/test/core/junit5/OsSpecificTest.xml
This adds the ability to have specific `os-release` attributes in answer file elements so they will only be checked on that specified OS. If not, that element will not be checked in ExtractionTest's `checkAnswers()` method.
The current elements this `verifyOS()` check is applied to are:
- dataLength
- meta
- nometa
- data
- view
- noview
(Had to alter the original `dataLength` check, because the old check did not assume multiple dataLength tags in the answer file. With this we are assuming data lengths could be different across different OS, meaning multiple tags _could_ be possible)
=> adding ability to ExtractionTest to have OS specific answers in test answer files

src/main/java/emissary/util/PlaceComparisonHelper.java
PlaceComparisonHelper was originally written such that it would not compare "dispose runnables". I now think we should compare "dispose runnables" so this PR makes that change.
=> Update PlaceComparisonHelper to compare "dispose runnables".

src/test/java/emissary/test/core/junit5/RegressionTest.java
This PR adds the actual "resource" (i.e. test file) being tested to the getEncoders()/getDecoders() calls.  This allows classes extending RegressionTest and overriding getEncoders()/getDecoders() to know which "resource" is being tested and return different Encoders/Decoders for different "resources". The methods without the "resource" parameter are deprecated for future deletion.
=> allow RegressionTest getEncoders/getDecoders to vary per "resource"

src/main/java/emissary/util/PlaceComparisonHelper.java, src/test/java/emissary/place/ComparisonPlaceTest.java
I noticed that the New/Old output order for PlaceComparisonHelper was reversed compared to the input order. This PR makes them match.
=> Reverse New/Old IBDO output to match input order in PlaceComparisonHelper.

src/main/java/emissary/core/IBaseDataObjectHelper.java
This PR exposes the "useSbcf" attribute on the addParentInformation... methods so that one can choose whether the IBDO.getChannelFactory() or IBDO.data() method is used to hash the payload.
=> expose the ability to choose SBCF/byte[] for addParentInformation...()

pom.xml, src/assembly/dist.xml
This will enforce compile scope dependencies are properly declared.
- jersey-common is transitive and will be brought in by jersey-server
- jersey-hk2 is only needed at runtime
- runtime dependencies were not packaged as part of distribution (follow-on to clean that up)
=> enforce analyzed compile scope dependencies

src/main/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/main/java/emissary/core/constants/IbdoMethodNames.java, src/test/java/emissary/core/IBaseDataObjectDiffHelperTest.java
The current implementation relies on reflection to access IBDO methods. This approach, however, is being replaced with direct method calls to improve robustness and maintainability. Reflection, while flexible, introduces fragility due to its reliance on string-based method lookups. These string representations can easily break during refactoring, leading to unexpected errors and runtime failures. By shifting to direct method calls, we eliminate this risk and ensure that method invocations remain intact even as the codebase evolves. This transition not only enhances the reliability of the system but also improves its overall performance by bypassing the overhead associated with reflection.
=> regression :: updated IbdoMethodNames to use BiConsumers

pom.xml, src/test/java/emissary/server/mvc/EndpointTestBase.java
- mockito-junit-jupiter isn't used
- jersey-test-framework-provider-jetty is required for mvc tests using EndpointTestBase/JerseyTest, but is discovered rather than imported. Registering the class that is ultimately being used gets around that
- the pom can now move from `ignoreNonCompile` to `ignoreUnusedRuntime` since that's the only remaining scenario
=> enforce analyzed test scope dependencies

src/main/java/emissary/kff/Ssdeep.java, src/main/java/emissary/transform/decode/JsonEscape.java, src/main/java/emissary/util/Hexl.java, src/main/java/emissary/util/xml/AbstractJDOMUtil.java
Suppressed the warnings in places where the parentheses seemed useful/needed.
Removed parentheses from JsonEscape as they were not necessary.
This resolves all remaining pmd UselessParentheses warnings.
=> pmd :: UselessParentheses

.github/workflows/maven-release.yml
The site step never worked and is not something we need to try and resolve/maintain
=> remove maven site publish from release workflow

src/main/java/emissary/directory/DirectoryPlace.java, src/main/java/emissary/jni/JniRepositoryPlace.java, src/main/java/emissary/util/ConstructorLookupCache.java
this pr suppresses these pmd warnings.
https://docs.pmd-code.org/pmd-doc-7.3.0/pmd_rules_java_errorprone.html#avoidbranchingstatementaslastinloop
this is one warning where I could see adding in the properties to the pmd xml file could be helpful in the future, but for now since there are only three instances, I figured I'd go with suppression. If we'd prefer the properties, I can add them in.
=> pmd :: AvoidBranchingStatementAsLastInLoop

src/main/java/emissary/parser/SessionProducer.java, src/main/java/emissary/pickup/PickUpPlace.java
this was noticed through the pmd UnusedFormalParameter warnings, as `myKey` was not was not used from the method signature with all uses in the class being commented out.
=> removing obsolete myKey value from SessionProducer constructor

src/main/java/emissary/place/ServiceProviderRefreshablePlace.java, src/main/java/emissary/server/EmissaryServer.java
This mechanism, similar to the Apache Commons FileAlterationMonitor, triggers registered FileAlterationObservers when files are changed. However, it operates on-demand, only checking for alterations when explicitly invoked at specified intervals and when the place is invoked, as opposed to the continuous monitoring employed by the FileAlterationMonitor.
Polling the file system for changes at predetermined intervals, this mechanism does not depend on the operating system's native file change notification events. This on-demand approach can be more resource-efficient, especially when file changes are infrequent, and can lead to reduced overhead and potentially better performance due to the absence of continuous monitoring and event handling.
Important Note: This on-demand mechanism may …
=> refresh :: add monitoring code to detect config changes

pom.xml
=> dependencies: bump commons-io from 2.17.0 to 2.19.0

pom.xml
=> dependencies: bump commons-codec from 1.16.0 to 1.18.0

pom.xml
=> dependencies: bump restrict-imports-enforcer-rule plugin from 2.3.1 to 2.6.1

pom.xml
This was previously not possible as 4.x required jdk 11. Then I believe we had some artifacts that needed upgrading first to get out of the older sun activation libraries. I believe we have moved past all that and now this is possible. 
```
>	angus-activation-2.0.2.jar
istack-commons-runtime-4.0.1.jar			      |	istack-commons-runtime-4.1.2.jar
jakarta.activation-2.0.1.jar				      |	jakarta.activation-api-2.1.3.jar
jakarta.xml.bind-api-3.0.1.jar				      |	jakarta.xml.bind-api-4.0.2.jar
jaxb-core-3.0.1.jar					      |	jaxb-core-4.0.5.jar
jaxb-runtime-3.0.1.jar					      |	jaxb-runtime-4.0.5.jar
txw2-3.0.1.jar						      |	txw2-4.0.5.jar
```
=> update to jaxb runtime 4.x

src/main/java/emissary/core/channels/InputStreamChannelFactory.java, src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java
Helps prevent IOExceptions in cases for which the source data is truncated to a size smaller than expected.  This behavior might not always be desirable, so it's an optional constructor argument that defaults to the previous behavior.
=> Added InputStreamChannelFactory optional support for bounded sizing

src/main/java/emissary/grpc/pool/ConnectionFactory.java, src/test/java/emissary/grpc/pool/ConnectionFactoryTest.java
PR to address suggested updates from @drewfarris for NationalSecurityAgency/Emissary#1142:
* Changed instances of "ms" to "millis" for improved clarity
* Included assertions for FIFO in pool retrieval order tests
=> gRPC connection factory additional formatting changes

src/main/java/emissary/kff/KffDataObjectHandler.java, src/main/java/emissary/place/KffHashPlace.java, src/main/resources/emissary/place/KffHashPlace.cfg, src/test/java/emissary/kff/KffDataObjectHandlerTest.java
Leveraging KffDataObjectHandler, create a new hash metadata field with the name HASH_ID. The field name should be configurable as well as the option to enable or disable the creation.
Create a murmur3 128 bit hash off the input of md5sum()-sha1sum()-sha256sum()
Original request code snippet so we can ensure the output matches the requested formatting:
```java
public static String getFileUUIDFromHashes(String md5, String sha1, String  sha256) {
HashFunction hashFunction = Hashing.murmur3_128();
HashCode hashCode = hashFunction.newHasher()
.putString(md5, UTF_8)
.putString(sha1, UTF_8)
.putString(sha256, UTF_8)
.hash();
return new StringBuilder(hashCode.toString())
.insert(20, "-")
.insert(16, "-")
.insert(12, "-")
.insert(8, "-")
.toString();
}
```
=> add murmur hash 'HASH_ID' to KffDataObjectHandler

src/test/java/emissary/core/IBaseDataObjectXmlCodecs.java, src/test/java/emissary/core/IBaseDataObjectXmlHelper.java, src/test/java/emissary/core/constants/IbdoMethodNames.java, src/test/java/emissary/core/constants/IbdoXmlElementNames.java, src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/java/emissary/test/core/junit5/RegressionTest.java
Builds on #1153 -- updating setupPayload to use the IBaseDataObjectXmlHelper class to parse the answer file. Had to move the encoder/decoder methods up to ExtractionTest. Also, removed `processHeavyDutyHook` in RegressionTest as it was almost identical to the overridden method.
=> regression-test :: move encoders/decoders to ExtractionTest and update to use IBaseDataObjectXmlHelper

pom.xml, src/test/java/emissary/config/ServiceConfigGuideTest.java, src/test/java/emissary/test/core/junit5/UnitTest.java
We can't assume '/tmp' works for unit testing everywhere due to possible security restrictions executing from '/tmp'. This should be configurable for those who require it. 
Adding this to the argline for surefire allows for proper promotion to the forked processes.
This also cleans up some variables:
- TEMP_DIR (how we reference in cfg files)
- TMPDIR (how we reference via env)
- TMP_DIR (is confusing and should be removed)
=> use 'java.io.tmpdir' location for unit tests

src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/resources/emissary/test/core/junit5/OsSpecificTest.xml, src/test/resources/emissary/test/core/schemas/answers.xsd
adding ability to have OS specific `<numAttachments>` & `<att#>` in test answer files.
=> adding OS specific checks to attachment elements in ExtractionTest
