README.md
=> Resolve typo

src/main/java/emissary/util/search/ByteMatcher.java, src/main/java/emissary/util/search/KeywordScanner.java, src/test/java/emissary/util/search/ByteMatcherTest.java, src/test/java/emissary/util/search/KeywordScannerTest.java
Added ability to reset byte data operated on by ByteMatcher and KeywordScanner
=> Added ability to reset byte data

src/main/java/emissary/id/TikaFilePlace.java, src/main/resources/emissary/id/TikaFilePlace.cfg
Added possibility to configure multiple Tika signature files, and TikaFilePlace now includes filename in media type detection.
=> Filename Tika detection and multiple Tika Signatures

src/main/java/emissary/pickup/WorkBundle.java, src/main/java/emissary/pickup/WorkUnit.java, src/main/java/emissary/pickup/file/FilePickUpClient.java, src/test/java/emissary/pickup/WorkBundleTest.java, src/test/java/emissary/pickup/WorkUnitTest.java
WorkBundle will have a list of WorkUnit.
=> Updated WorkBundle for TransactionManager. Created WorkUnit class

contrib/checkstyle.xml, pom.xml
- breaking and deprecated changes from the 8.x series needed updates
- advance to latest available
=> upgrade checkstyle

src/main/java/emissary/util/io/UnitTestFileUtils.java, src/test/java/emissary/client/EmissaryClientTest.java, src/test/java/emissary/config/ConfigUtilTest.java, src/test/java/emissary/config/FTestServiceConfigGuide.java, src/test/java/emissary/config/ServiceConfigGuideTest.java, src/test/java/emissary/parser/SimpleNioParserTest.java, src/test/java/emissary/place/MainTest.java, src/test/java/emissary/place/MultiFileUnixCommandPlaceTest.java, src/test/java/emissary/place/ServiceProviderPlaceTest.java, src/test/java/emissary/place/UnixCommandPlaceTest.java, src/test/java/emissary/util/MagicNumberUtilTest.java, src/test/java/emissary/util/roll/RollableFileOutputStreamTest.java
Breaking https://github.com/NationalSecurityAgency/emissary/pull/34 into smaller PRs
=> update tests to use java nio

src/main/java/emissary/output/DropOffUtil.java, src/test/java/emissary/output/DropOffUtilTest.java
=> DropOffUtil now stores only unique non-null FILEXT values

README.md, contrib/docker/Dockerfile.dev
Helps me test the code base with Centos/Maven/Java since I am on a Mac.
=> centos-7 docker dev image with maven-3 and corretto-java-1.8.0

.github/workflows/maven.yml, .gitignore, README.md
Also adds VSCode IDE dir to gitignore, fixes a minor typo in readme
=> (Minor) Update GitHub actions workflow

pom.xml, src/main/java/emissary/util/MagicNumberUtil.java, src/main/java/emissary/util/magic/MagicNumber.java, src/main/java/emissary/util/magic/MagicNumberFactory.java
Moving magic classes to use slf4j and parameterized statements for logging.
I could be convinced to leave the pom config alone.
=> Parameterize log statements in MagicNumber classes

src/main/java/emissary/util/PayloadUtil.java, src/test/java/emissary/util/PayloadUtilTest.java
Addresses an accidental omission in PR #158
=> Added parentheses to the set of acceptable characters in an IBDO Form name

src/main/java/emissary/place/MultiFileUnixCommandPlace.java
Removed lines with possible content logging within MultiFileUnixCommandPlace.
=> Removed content logging within MultiFileUnixCommandPlace

src/main/java/emissary/output/DropOffUtil.java
Removed logging of content and unnecessary logging. Also cleaned up remaining log lines.
=> Removed content logging in DropOffUtil

.github/workflows/codeql-analysis.yml
v1 will be deprecated in December 2022
=> Upgrade github CodeQL to v2

src/test/java/emissary/server/api/PeersIT.java, src/test/java/emissary/server/api/PlacesTest.java
=> remove unused imports

pom.xml
Resulting sorted pom due to addition of:
```
<sortDependencyExclusions>scope,groupId,artifactId</sortDependencyExclusions>
<sortPlugins>groupId,artifactId</sortPlugins>
```
=> add plugin and exclusion sorting to pom file

src/test/java/emissary/test/core/UnitTest.java, src/test/java/emissary/util/shell/ExecutrixTest.java
I did see some other classes that use System.getProperty, but they necessarily need "/tmp" at the moment. Is the scope of this ticket to change how those classes work as well?
=> B1603: Abstracted creation of temp directories for a couple of test classes

src/main/java/emissary/command/RunCommand.java, src/main/java/emissary/command/WhatCommand.java, src/main/java/emissary/place/Main.java
I'd like to remove these concepts in 8
=> deprecate :: main and run/what commands

src/main/java/emissary/client/EmissaryClient.java, src/main/java/emissary/command/converter/WorkspaceSortModeConverter.java, src/main/java/emissary/command/validator/ServerModeValidator.java, src/main/java/emissary/config/ServiceConfigGuide.java, src/main/java/emissary/core/HDMobileAgent.java, src/main/java/emissary/id/TikaFilePlace.java, src/main/java/emissary/id/UnixFilePlace.java, src/main/java/emissary/kff/KffChainLoader.java, src/main/java/emissary/kff/KffMemcached.java, src/main/java/emissary/kff/Ssdeep.java, src/main/java/emissary/output/filter/AbstractFilter.java, src/main/java/emissary/parser/FillingNIOParser.java, src/main/java/emissary/parser/NIOSessionParser.java, src/main/java/emissary/transform/HtmlEscapePlace.java, src/main/java/emissary/transform/decode/HtmlEscape.java, src/main/java/emissary/transform/decode/JavascriptEscape.java, src/main/java/emissary/transform/decode/JsonEscape.java, src/main/java/emissary/util/ConstructorLookupCache.java, src/main/java/emissary/util/HtmlEntityMap.java, src/main/java/emissary/util/MagicNumberUtil.java, src/main/java/emissary/util/MetadataDictionaryUtil.java, src/main/java/emissary/util/TypeEngine.java, src/main/java/emissary/util/WindowedSeekableByteChannel.java, src/main/java/emissary/util/magic/MagicNumber.java, src/main/java/emissary/util/shell/ReadOutputLogger.java
Cleaned up content/unnecessary logging found throughout the entirety of the Emissary program. Any classes that were altered, I went through and parameterized all logs in that given class.
_*Any files with open content logging PRs not included*_
=> Cleaned up content/unnecessary logging - Emissary Logs

pom.xml
Reverts NationalSecurityAgency/emissary#294
=> Revert "(Minor) Use native git with commit-id plugin"

src/test/java/emissary/util/PlaceComparisonHelperTest.java
These tests turned out to be slightly flaky in rare occurrences, believe the underlying cause has now been addressed.
=> Fix flaky tests in PlaceComparisonHelperTest

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObjectHelper.java, src/main/java/emissary/core/channels/AbstractSeekableByteChannel.java, src/main/java/emissary/core/channels/FileChannelFactory.java, src/main/java/emissary/core/channels/FillChannelFactory.java, src/main/java/emissary/core/channels/InputStreamChannelFactory.java, src/main/java/emissary/core/channels/SeekableByteChannelHelper.java, src/main/java/emissary/util/DisposeHelper.java, src/main/java/emissary/util/PlaceComparisonHelper.java, src/test/java/emissary/core/BaseDataObjectTest.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java, src/test/java/emissary/core/channels/AbstractSeekableByteChannelTest.java, src/test/java/emissary/core/channels/FileChannelFactoryTest.java, src/test/java/emissary/core/channels/FillChannelFactoryTest.java, src/test/java/emissary/core/channels/ImmutableChannelFactoryTest.java, src/test/java/emissary/core/channels/InputStreamChannelFactoryTest.java, src/test/java/emissary/core/channels/SeekableByteChannelHelperTest.java, src/test/java/emissary/kff/ChecksumCalculatorTest.java, src/test/java/emissary/util/PlaceComparisonHelperTest.java, src/test/java/emissary/util/TestMinimalServiceProviderPlace.java
This PR contains follow-on work identified as non-critical fixes or wider changes from #204.
=> Large data - follow-up/phase 2 work

DEVELOPING.md, contrib/docker/Dockerfile.alpine
I needed a lighter-weight Emissary image for a project. I figured I would share.
This is something the team will probably never use. So if we don't want it as part of the main repo I understand and it can just live in my fork :)
=> Create lightweight alpine Dockerfile

src/main/java/emissary/command/AgentsCommand.java, src/main/java/emissary/command/BaseCommand.java, src/main/java/emissary/command/EmissaryCommand.java, src/main/java/emissary/command/EnvCommand.java, src/main/java/emissary/command/FeedCommand.java, src/main/java/emissary/command/HttpCommand.java, src/main/java/emissary/command/MonitorCommand.java, src/main/java/emissary/command/PeersCommand.java, src/main/java/emissary/command/PoolCommand.java, src/main/java/emissary/command/ServerCommand.java, src/main/java/emissary/command/TopologyCommand.java
Reorders the command classes so all of the jcommander parameters are together in the file. Added some helper methods to deduplicate some code blocks as well.
=> cleaned up some of the emissary commands

README.md
To give quick insight into the status of the main branch from the repo homepage
=> Add github action status to readme

src/main/java/emissary/core/channels/LoggingInputStreamFactory.java, src/test/java/emissary/core/channels/LoggingInputStreamFactoryTest.java
This PR creates an InputStreamFactory that wraps another InputStreamFactory and logs every method call on any InputStreams that are created. This is intended only for Development/Debugging purposes.
=> Create a LoggingInputStreamFactory.

src/main/java/emissary/core/channels/LoggingChannelFactory.java, src/test/java/emissary/core/channels/LoggingChannelFactoryTest.java
This PR creates a SeekableByteChannelFactory that wraps another SeekableByteChannelFactory and logs every method call on any SeekableByteChannels that are created. This is intended only for Development/Debugging purposes.
=> Creates a LoggingChannelFactory.

src/main/java/emissary/kff/KffChainLoader.java, src/main/java/emissary/kff/KffFile.java, src/main/java/emissary/kff/KffQuincyFile.java, src/main/java/emissary/kff/Ssdeep.java, src/main/java/emissary/util/Hexl.java, src/main/java/emissary/util/Version.java, src/test/java/emissary/kff/KffDataObjectHandlerTest.java, src/test/java/emissary/test/core/ExtractionTest.java, src/test/java/emissary/test/core/IdentificationTest.java, src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/java/emissary/test/core/junit5/IdentificationTest.java
These calls are all in main methods or tests, so should not have any impact.
=> sonar :: check the return value of InputStream#read(byte[]) (bug)

pom.xml
=> build :: set the mvn javadoc plugin to fail on warning/error

pom.xml
Run with:
```
mvn clean pmd:check
```
or with the regular build:
```
mvn clean verify
```
=> build :: set the mvn pmd plugin to fail on violations

contrib/docker/Dockerfile, contrib/docker/Dockerfile.dev
Intentionally leaving the Alpine image to openjdk. Going to need a few more changes in order to install corretto.
=> Update dockerfiles to use java 11

pom.xml
=> update jetty to 9.4.51.v20230217

.github/workflows/dependency-review.yml
Got this as a recommended action for PR's and since I am going through and updating actions might as well add another one!
=> add dependency review action

src/main/java/emissary/core/MobileAgent.java, src/main/java/emissary/core/Stage.java, src/test/java/emissary/core/StageTest.java
=> Refactor Stage to be an enum (Closes #1877)

src/main/config/emissary.roll.RollManager.cfg, src/main/java/emissary/metrics/AgentsEmitter.java
Defaulted to off. This is meant to be illustrative, but does provide info messages when activated.
=> Add an AgentEmitter class to output agent status

src/main/java/emissary/core/HDMobileAgent.java, src/main/java/emissary/core/MobileAgent.java
This builds on https://github.com/NationalSecurityAgency/emissary/pull/485 but migrates all calls of this method to use the idle state boolean rather than a synchronized method.
=> update MobileAgent isInUse method to use idle boolean

pom.xml
also helps to sync on the same jetty-continuation.jar version
=> manage jetty deps using the jetty-bom

pom.xml
Replacing: https://github.com/NationalSecurityAgency/emissary/pull/372
=> Small pom updates for compliance with maven repositories

src/main/java/emissary/util/TimeUtil.java, src/test/java/emissary/util/TimeUtilTest.java
Issue: https://github.com/NationalSecurityAgency/burrito-grande/issues/2330
=> Make enhancements to convertHexDate

src/main/java/emissary/client/EmissaryResponse.java, src/main/java/emissary/command/BaseCommand.java, src/main/java/emissary/core/Factory.java, src/main/java/emissary/pickup/WorkSpace.java, src/test/java/emissary/command/BaseCommandTest.java, src/test/java/emissary/command/RunCommandIT.java, src/test/java/emissary/command/ServerCommandIT.java, src/test/java/emissary/test/core/UnitTest.java, src/test/java/emissary/test/core/junit5/UnitTest.java
…with clazz.getDeclaredConstructor().newInstance()
conflicts with #568
=> replace the call clazz.newInstance()

pom.xml, src/test/java/emissary/core/channels/FillChannelFactoryTest.java
closes https://github.com/NationalSecurityAgency/emissary/security/dependabot/23
=> remove bouncycastle dependency

.github/workflows/linter.yaml, .github/workflows/mega-linter.yaml
Fork of SuperLinter that provides drop in replacement and potentially more features.
Has a more active community... and is currently certified.
https://github.com/marketplace/actions/megalinter
=> Replace Super Linter with Mega Linter

README.md
workflow file name changed and needed to be updated in the readme
=> Correct maven CI badge in README.md

src/main/java/emissary/server/EmissaryServer.java
While working on other Startup things in Emissary, saw some sonarlint complaints in EmissaryServer that were easy fixes that I thought would be good to make.
Didn't make any of the possible major changes, just small tech-debt.
=> Simple EmissaryServer Clean-up

.github/release.yml
This adds auto formatting to the Releases github page
=> Add github release yml file

pom.xml
No noticeable changes in the test output
Release notes:
https://junit.org/junit5/docs/5.10.0/release-notes/index.html
https://junit.org/junit5/docs/5.9.0-M1/release-notes/
https://github.com/mockito/mockito/releases/tag/v5.5.0
=> Junit and Mockito updates

src/main/java/emissary/core/IBaseDataObjectHelper.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java
This PR improves the testing of findPreferredData(...) and findPreferredDataByRegex(...) methods.
=> Improve IBaseDataObjectHelper testing.

src/main/java/emissary/client/response/Directory.java, src/main/java/emissary/core/HDMobileAgent.java, src/main/java/emissary/core/IMobileAgent.java, src/main/java/emissary/core/MobileAgent.java, src/main/java/emissary/core/sentinel/Sentinel.java, src/main/java/emissary/directory/DirectoryEntry.java, src/main/java/emissary/directory/DirectoryEntryList.java, src/main/java/emissary/directory/DirectoryEntryMap.java, src/main/java/emissary/directory/DirectoryPlace.java, src/main/java/emissary/directory/HeartbeatManager.java, src/main/java/emissary/directory/KeyManipulator.java, src/main/java/emissary/place/CoordinationPlace.java, src/main/java/emissary/place/IServiceProviderPlace.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/main/java/emissary/server/mvc/DumpDirectoryAction.java, src/main/java/emissary/server/mvc/adapters/DirectoryAdapter.java, src/main/java/emissary/server/mvc/adapters/WorkSpaceAdapter.java, src/test/java/emissary/core/BogusHDAgent.java, src/test/java/emissary/core/FTestMovingAgent.java, src/test/java/emissary/core/ResourceWatcherTest.java, src/test/java/emissary/core/sentinel/SentinelTest.java, src/test/java/emissary/directory/DirectoryEntryListTest.java, src/test/java/emissary/directory/DirectoryEntryTest.java, src/test/java/emissary/directory/KeyManipulatorTest.java
Using the updates from https://github.com/NationalSecurityAgency/emissary/pull/648, updating error-prone MemberNames throughout the project.
=> Resolving error-prone MemberNames

pom.xml
Test cases look good.
Release notes:
https://commons.apache.org/proper/commons-codec/changes-report.html#a1.16.0
Drafting pending further verification.
=> commons-codec 1.15 -> 1.16.0

pom.xml
=> add plugin to generate sbom

src/main/java/emissary/core/IBaseDataObjectHelper.java, src/test/java/emissary/core/IBaseDataObjectHelperTest.java
Adds method to copy metadata from parent to child while specifying parameters not to copy
=> New method to copy metadata from parent to child with exclusions

src/main/java/emissary/util/magic/MagicNumber.java, src/main/java/emissary/util/magic/MagicNumberFactory.java, src/test/java/emissary/pickup/file/FilePickUpClientTest.java, src/test/java/emissary/test/core/junit5/LogbackTester.java
Simple pr to resolve error-prone `MissingBraces`. Parent issue: https://github.com/NationalSecurityAgency/burrito-grande/issues/2600
=> resolve error-prone MissingBraces

.github/workflows/maven-release.yml
Fixies problems introduced when adding slack message notifications in last milestone release
=> github-actions :: version in env, slack-bot message format

src/main/java/emissary/core/BaseDataObject.java, src/main/java/emissary/core/IBaseDataObject.java, src/test/java/emissary/core/BaseDataObjectTest.java
This PR adds a method to IBaseDataObject and BaseDataObject that checks whether there is valid data and that it is non-zero in length.
=> Add IBDO method to ensure data is available.

pom.xml
Output now: 
```
186 [FieldMissingNullable]
131 [MemberName]
121 [ReturnMissingNullable]
105 [NonFinalStaticField]
102 [ParameterMissingNullable]
94 [ConstantField]
93 [UnnecessarilyFullyQualified]
88 [SystemOut]
85 [UngroupedOverloads]
68 [AvoidObjectArrays]
57 [MissingBraces]
54 [UnnecessaryParentheses]
51 [InconsistentOverloads]
51 [CatchingUnchecked]
41 [FieldCanBeFinal]
37 [StringCaseLocaleUsage]
34 [MethodCanBeStatic]
34 [JavaUtilDate]
27 [CanIgnoreReturnValueSuggester]
26 [ThrowSpecificExceptions]
26 [MissingSummary]
22 [CheckedExceptionNotThrown]
20 [UnusedVariable]
19 [InterruptedExceptionSwallowed]
17 [ThreadPriorityCheck]
17 [StringSplitter]
17 [JdkObsolete]
14 [FieldCanBeStatic]
13 [MissingOverride]
12 [DeduplicateConstants]
10 [ThrowsUncheckedException]
9 …
```
=> set unlimited maxerrs and maxwarns for error prone

.github/linters/.mega-linter.yml
This will stop fixes from being applied and hidden by the action. Instead it will outline changes that are needed during the PR check so that the author can make them.
=> megalinter :: disable action applying fixes

src/main/java/emissary/util/CharacterCounterSet.java
a symptom of rebasing but luckily non-impactful
=> remove unreachable code block in CharacterCounterSet

.github/workflows/maven-ci.yml, .github/workflows/maven-release.yml
Example run: https://github.com/cfkoehler/emissary/actions/runs/8606369859
=> Skip slack notifications if running on a fork

.github/workflows/maven-release.yml
This matches the other instances of the same message. If '_' or '-' is preferred, let me know.
=> update action name syntax for release

src/main/java/emissary/core/TransformHistory.java, src/main/java/emissary/core/sentinel/protocols/rules/AllMaxTime.java, src/main/java/emissary/core/sentinel/protocols/rules/AnyMaxTime.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/main/java/emissary/util/shell/Executrix.java, src/main/java/emissary/util/shell/ProcessReader.java, src/test/java/emissary/pickup/file/FilePickUpClientTest.java
Adding MissingOverride and removed RedundantOverride. Adding the missing override also cleared out some sonar complaints.
=> errorprone :: MissingOverride & RedundantOverride

src/main/java/emissary/output/filter/JsonOutputFilter.java, src/main/java/emissary/output/roller/journal/JournalReader.java, src/test/java/emissary/config/FTestServiceConfigGuide.java, src/test/java/emissary/core/BaseDataObjectTest.java, src/test/java/emissary/output/roller/journal/JournalTest.java, src/test/java/emissary/test/core/junit5/ExtractionTest.java, src/test/java/emissary/util/DataUtilTest.java, src/test/java/emissary/util/io/UnitTestFileUtils.java
=> errorprone :: PreferredInterfaceType

src/main/java/emissary/pickup/PickUpPlace.java
Address a sonarlint bug for enforcing end conditions on while loops
https://rules.sonarsource.com/java/RSPEC-2189/
I believe this is more of an issue with sonarlint's ability to understand that there IS an end condition in that a ParserEOFException WILL be thrown to end the loop, but that could speak to the ability to programmatically guarantee such a concept. This doesn't attempt to address that fundamental behavior since that's just the pattern we have. 
I do like the fact that adding a `boolean` makes it more clear to the reader what condition ends the loop instead of looking for `break` statements.
=> sonarlint :: add end condition to while loop in PickUpPlace

src/main/java/emissary/admin/PlaceStarter.java, src/main/java/emissary/core/sentinel/protocols/actions/Exit.java, src/main/java/emissary/output/filter/AbstractRollableFilter.java, src/main/java/emissary/roll/RollManager.java, src/main/java/emissary/server/api/Shutdown.java
Suppressed these warnings in the places where they should be kept instead of turning off the warning.
=> errorprone :: SystemExitOutsideMain

src/main/java/emissary/output/DropOffPlace.java
Resolves negative duration in log messages
=> DropOffPlace: Corrected order of Duration.between(...) arguments

src/main/java/emissary/util/TimeUtil.java
I'm not married to the use of the annotation in this case, but I'm pretty sure this one has impacts downstream.
=> errorprone :: MemberName - TimeUtil

src/test/java/emissary/test/core/junit5/UnitTest.java
I think this has far too many touch points in the test code to update right now
=> errorprone :: ConstantField - UnitTest.TMPDIR

src/main/java/emissary/core/channels/ConcatenateChannelFactory.java, src/test/java/emissary/core/channels/CheckCloseChannelFactory.java, src/test/java/emissary/core/channels/ConcatenateChannelFactoryTest.java, src/test/java/emissary/core/channels/ExceptionChannelFactory.java, src/test/java/emissary/core/channels/SegmentChannelFactoryTest.java
This PR adds the ConcatenateChannelFactory which concatenates two SeekableByteChannelFactory instances.
=> Add ConcatenateChannelFactory for seekable byte channels

src/main/java/emissary/parser/DataIdentifier.java
related to: https://github.com/NationalSecurityAgency/emissary/pull/872
=> revert DATA_ID_STR_SZ field change

src/main/java/emissary/kff/KffDataObjectHandler.java
Guards against superfluous `kff.hash(...)` calls
=> No longer preserving MD5_ORIGINAL if re-hashing hasn't changed the value

src/test/java/emissary/pickup/FTestMultipleWorkSpaces.java, src/test/java/emissary/pickup/FTestWorkSpaceMaxBundleSize.java, src/test/java/emissary/pickup/file/FTestSpacePlaceInteraction.java
FTests need to be refactored, so ignore warnings for now.
=> errorprone :: ignore FTest warnings

pom.xml
Adding to match other repos and set up for more exclusions.
S6212 details: https://next.sonarqube.com/sonarqube/coding_rules?open=java%3AS6212&rule_key=java%3AS6212
=> add global sonar exclusion for rule s6212

src/main/java/emissary/config/ExtractResource.java, src/main/java/emissary/core/ExtractedRecord.java, src/main/java/emissary/place/CoordinationPlace.java, src/main/java/emissary/util/CharsetUtil.java
SystemOut
ReturnsNullCollection
StringCharset
UngroupedOverloads
=> errorprone: misc fixes

src/main/java/emissary/util/search/ByteMatcher.java, src/main/java/emissary/util/search/KeywordScanner.java, src/test/java/emissary/util/search/ByteMatcherTest.java, src/test/java/emissary/util/search/KeywordScannerTest.java
Adding the ability to search for occurrences of a pattern and return a list of positions in which the pattern starts.
=> Adding listIndexOf method to KeywordScanner

pom.xml
Aligns with profile naming convention
=> change errorprone profile name

src/main/java/emissary/place/CoordinationPlace.java
This helped with debugging something yesterday. 
Don't really care if we accept it or not
=> add debug message when setting the form in CoordinationPlace

src/main/java/emissary/command/converter/PriorityDirectoryConverter.java
Moved Pattern and Matcher to make class level vars to save regex complie time
=> pre-compile regex in PriorityDirectoryConverter

src/main/java/emissary/core/IBaseDataObject.java
```
/opt/emissary/src/main/java/emissary/core/IBaseDataObject.java:[420,8] [ReturnMissingNullable] Method returns a definitely null value but is not annotated @Nullable
```
=> add Nullable to new getParameterAsConcatString method

src/main/java/emissary/core/IBaseDataObject.java, src/test/java/emissary/core/channels/ChannelTestHelper.java
removes pmd warnings for unnecessary semicolons
=> pmd :: UnnecessarySemicolon

pom.xml
move from using JUnit Jupiter dependencies to using the JUnit BOM
=> use JUnit 5.11.4 bom

contrib/repo-manual-mirror.sh
same util that is used in upstream to help with source code management
=> add script to create a tarball of the git repo

contrib/pmd/maven-pmd-plugin-default.xml, src/main/java/emissary/util/DependencyCheck.java, src/test/java/emissary/client/HTTPConnectionFactoryTest.java, src/test/java/emissary/test/core/junit5/TestExtractionTest.java, src/test/java/emissary/util/FlexibleDateTimeParserTest.java
Commented out UnnecessaryFullyQualified rule.
- in very few cases, actually removing the fully qualified name, only if it seemed useless/Assertions in testing classes.
=> pmd :: UnnecessaryFullyQualifiedNames

src/main/java/emissary/util/magic/MagicNumberFactory.java
noticed this class could use some TLC while going through pmd stuff.
Generally made simple changes. There are a lot of `null` checks in this class on things that explicitly cannot be null, so further clean-up could be done, but I left _most_ of those for now.
=> code clean-up in MagicNumberFactory

src/main/java/emissary/kff/KffFile.java, src/main/java/emissary/util/magic/MagicNumber.java
suppressing pmd warnings for unused private methods
=> pmd :: UnusedPrivateMethod

src/main/java/emissary/kff/KffMemcached.java, src/main/java/emissary/place/ServiceProviderPlace.java, src/test/java/emissary/core/FTestMobileAgent.java, src/test/java/emissary/pickup/BreakableFilePickUpClient.java, src/test/java/emissary/place/OOMPlace.java, src/test/java/emissary/test/core/junit5/UnitTest.java
suppressing warnings as to not change method signatures
=> pmd :: UnusedFormalParameter

src/main/java/emissary/kff/Ssdeep.java, src/main/java/emissary/roll/Roller.java
follow-up to https://github.com/NationalSecurityAgency/emissary/pull/1061
ended up just suppressing the warning in SsDeep, and going through and doing the split up in Roller suggested in the review on 1061.
=> pmd :: CollapsibleIfStatement

pom.xml
This reduces the updates reported when doing a versions check
```
mvn versions:display-dependency-updates
```
=> add ignored suffix values for versions plugin

pom.xml
=> dependencies: bump dropwizard metrics from 4.2.25 to 4.2.30

pom.xml
=> dependencies: bump junit to 5.12.2 and mockito to 5.17.0

pom.xml
=> dependencies: bump jackson from 2.15.2 to 2.18.3

pom.xml
=> dependencies: bump commons-exec from 1.3 to 1.4.0

src/main/java/emissary/parser/SessionProducer.java, src/main/java/emissary/pickup/PickUpPlace.java
creating SessionProducer that defaults intialForms to null.
Also changed applicable places in emissary where this could be used.
=> add SessionProducer constructor that defaults to null initialForm

src/main/java/emissary/place/ServiceProviderPlace.java, src/test/java/emissary/place/ServiceProviderPlaceTest.java
This somewhat goes along with #1136. I just think it'll make unit testing easier.
=> Added Configurator constructor to ServiceProviderPlace

src/test/java/emissary/test/core/junit5/RegressionTest.java, src/test/java/emissary/test/core/junit5/UnitTest.java, src/test/resources/emissary/test/core/schemas/regression.xsd, src/test/resources/emissary/test/core/schemas/xml.xsd
Introducing a regression test answer schema to provide a basis for comparison with the extraction test answer schema.
=> tests :: add schema for regression test answers

src/main/java/emissary/Emissary.java, src/main/java/emissary/command/VersionCommand.java, src/main/java/emissary/server/api/Version.java, src/main/java/emissary/util/GitRepositoryState.java
output changes from
`Emissary Version: 8.33.0-SNAPSHOT 2025-09-26T14:22:15Z`
to
`Emissary Version: 8.33.0-SNAPSHOT - built on 2025-09-26T14:34:44Z - git hash: de96edc`
=> change version command output to include git hash
